
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 150
#define YY_END_OF_BUFFER 151
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[346] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  151,  149,
       67,    1,  127,   50,  149,  149,  129,   33,  141,  142,
      130,  132,  145,  131,  136,  139,    6,  149,  147,  146,
      137,  133,  138,  140,  148,  148,  143,  144,  128,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  135,  134,   48,   49,   34,
       49,   54,   66,   51,   54,   66,    5,    4,    3,   67,
      113,    0,  119,  114,  124,  117,  106,  120,  107,  121,
      105,    0,   24,    0,  118,    8,   24,   18,    0,    0,
        0,    7,    9,    0,    8,    0,    0,    0,    6,  108,

      110,  112,  111,  109,    0,  148,  148,    0,    0,  126,
      148,  148,  148,  148,  148,  148,  148,  148,  148,   77,
      148,  148,  148,  148,  148,  148,   85,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  125,  115,
       45,   35,   36,   44,   47,   38,   39,   40,   46,   41,
       42,   43,    0,   62,   63,   52,   61,   65,   55,   56,
       57,   64,   58,   59,   60,    0,    0,  116,    0,   25,
       26,    0,   24,   20,   19,   21,   20,    0,   27,   11,
       10,   12,  122,  123,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,   83,  148,

      148,   88,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,   35,   37,
       52,   53,    0,    0,   24,    0,   30,   23,   22,   27,
       28,   29,   14,    0,   13,   15,   12,  148,  148,  148,
       68,  148,   71,   72,  148,  148,  148,  148,   79,   80,
      148,  148,   84,  148,   89,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  102,  148,  148,
       35,   37,   52,   53,    2,   24,   31,   32,   28,    0,
       17,   16,   69,  148,  148,   70,   74,  148,  148,  148,
      148,   82,  148,  148,  148,  148,   93,  148,  148,  148,

      148,  148,  148,  100,  148,  148,  104,   25,  148,  148,
      148,  148,   78,   81,   87,  148,  148,   92,   94,   95,
       96,   97,   98,  148,  148,  148,  148,  148,  148,   76,
      148,  148,   99,  148,  148,   73,  148,   75,   90,   91,
      101,  103,  148,   86,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   28,   31,   32,
       33,   33,   34,   33,   33,   35,   33,   33,   33,   36,
       33,   33,   33,   33,   37,   33,   33,   38,   33,   33,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   33,   53,   54,   55,   56,
       57,   58,   33,   59,   60,   61,   62,   63,   64,   65,
       66,   67,    1,   68,    1,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    3,
        3,    1,    1,    1,    4,    1,    1,    3,    3,    3,
        3,    3,    5,    5,    5,    6,    5,    5,    1,    1,
        1,    1,    5,    3,    3,    3,    3,    3,    3,    5,
        5,    5,    5,    5,    5,    5,    5,    6,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    7,    1
    } ;

static const flex_int16_t yy_base[358] =
    {   0,
        0,    0,   67,   68,   69,   70,   76,   77,  414, 1004,
       84, 1004,  375, 1004,  389,  362,   65, 1004, 1004, 1004,
      348,   67, 1004,   71,   74,  327,  100,  152, 1004, 1004,
       74,  302,   75, 1004,  204,   72,   83, 1004,  298,  122,
      256,   54,  113,   79,  123,   61,  138,  159,  146,  126,
      193,  136,  149,  150,  141,  161, 1004, 1004, 1004, 1004,
      315, 1004, 1004, 1004, 1004,  375, 1004, 1004, 1004,  157,
     1004,  192, 1004, 1004, 1004, 1004, 1004, 1004, 1004, 1004,
     1004,  304,  422,  202, 1004, 1004,  220,  254,  274,   89,
      312, 1004,  285,    0,  108,  242,    0,  324,  335,  289,

     1004, 1004, 1004,  287,  266,  218,  199,  249,  347, 1004,
      214,  241,  262,  238,  290,  127,  331,  293,  181,  294,
      323,  360,  337,  333,  362,  365,  324,  394,  340,  427,
      392,  396,  415,  393,  367,  439,  430,  448, 1004,  109,
     1004,  397,  473, 1004, 1004, 1004, 1004, 1004, 1004, 1004,
     1004, 1004,    0, 1004, 1004,  227, 1004, 1004, 1004, 1004,
     1004, 1004, 1004, 1004, 1004,    0,  482, 1004,  492,  461,
     1004,  501,  201, 1004, 1004,  512,  125,  506,  516, 1004,
     1004,  522, 1004, 1004,  472,  487,  493,  488,  514,  501,
      518,  527,  307,  526,  524,  536,  535,  529,  468,  521,

      546,  537,  543,  547,  545,  550,  551,  564,  568,  562,
      579,  583,  585,  591,  557,  584,  590,  600,  607,    0,
      387,    0,  268,  618,  636,  641,  644, 1004, 1004,  650,
      387, 1004, 1004,  206, 1004,  638,    0,  612,  623,  628,
      604,  657,  607,  618,  626,  660,  166,  629,  671,  672,
      673,  683,  678,  686,  684,  685,  688,  690,  694,  700,
      702,  698,  692,  697,  710,  705,  713,  696,  706,  752,
      714, 1004, 1004, 1004, 1004,  756, 1004, 1004, 1004,  735,
     1004, 1004,  704,  762,  763,  714,  719,  766,  767,  769,
      768,  772,  775,  777,  773,  786,  778,  779,  780,  781,

      789,  801,  785,  787,  795,  792,  790, 1004,  791,  811,
      794,  815,  796,  797,  802,  844,  849,  851,  854,  855,
      856,  857,  858,  860,  863,  861,  865,  864,  868,  867,
      879,  873,  869,  871,  872,  874,  884,  876,  877,  880,
      881,  882,  885,  886, 1004,  954,  961,  968,  974,  980,
      986,  991,  223,  219,  157,  102,  996
    } ;

static const flex_int16_t yy_def[358] =
    {   0,
      345,    1,  346,  346,  347,  347,  348,  348,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  349,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  350,  350,  345,  345,  345,  350,
      350,   41,   41,   41,   41,   41,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  351,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  349,  345,  345,   83,   27,   28,  351,
      351,  345,  345,  352,  351,   28,   28,  345,  345,  345,

      345,  345,  345,  345,  349,   41,  350,  345,  345,  345,
      350,  350,  350,  350,  350,   41,  350,  350,   41,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  345,  351,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  353,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  354,  345,  345,  349,  349,
      345,  345,   87,  345,  345,  345,  351,  345,   91,  345,
      345,  352,  345,  345,  350,  350,  350,  350,  350,  350,
      350,  350,   41,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  345,  355,
      345,  356,  345,  345,   83,  345,  345,  345,  345,  345,
      351,  345,  345,  357,  345,  345,  182,  350,  350,  350,
      350,  350,  350,  350,  350,  350,   41,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  357,
      345,  345,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  345,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,    0,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345
    } ;

static const flex_int16_t yy_nxt[1074] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       28,   29,   30,   31,   32,   33,   34,   35,   35,   35,
       35,   35,   36,   36,   36,   36,   36,   36,   37,   10,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       36,   48,   36,   49,   36,   36,   36,   36,   50,   51,
       52,   53,   54,   55,   36,   36,   36,   56,   57,   59,
       59,   63,   63,   74,   64,   64,   60,   60,   68,   68,
       77,   69,   69,   65,   65,   70,   79,   70,  345,   75,
       82,   78,   83,   83,   83,   80,   81,  100,  101,  103,

      104,  108,  109,  109,  274,  105,   61,   61,   66,   66,
       86,   86,  115,  345,  124,  107,   87,  125,   88,   88,
       89,   98,  107,   99,  105,  105,  119,   90,   90,   90,
       91,   90,  345,  345,   92,  120,   93,   94,  345,  345,
      107,  105,  345,   90,   90,   90,   90,   91,   90,  345,
      111,  112,  345,   92,  345,  113,  116,  345,   70,  272,
       70,   93,  345,  117,   94,  345,  345,   95,   87,  118,
       96,   97,   97,  130,  107,  345,  121,  105,  122,   90,
       90,   90,   91,   90,  107,  139,  190,  123,  107,  345,
       98,  138,   99,  345,  126,   90,   90,   90,   90,   91,

       90,  135,  129,  345,  136,  345,  137,  127,  345,  345,
      167,  167,  167,  345,  128,  345,  345,  345,  345,   90,
      105,  222,  106,  106,  106,  220,  345,  289,  140,  193,
      345,  106,  106,  106,  106,  106,  172,  172,  173,  173,
      173,  172,  107,  131,  132,  221,  221,  106,  106,  106,
      106,  106,  106,  133,  345,  345,  134,  345,  172,  172,
      345,   96,   96,  172,  174,  174,  345,  108,  108,  108,
      185,   90,  105,  275,  106,  106,  106,  345,  345,  107,
      345,  345,  345,  106,  106,  106,  106,  106,  175,   99,
      176,  345,   89,   89,   89,  180,  180,  186,  188,  106,

      106,  106,  106,  106,  106,  345,  345,  175,  345,  345,
      345,  184,  345,  183,  345,  176,  187,  114,  345,  181,
      168,  177,  110,   90,  141,  178,  102,  178,  105,  345,
      179,  179,  179,  142,  142,  143,  345,  189,  181,  345,
      345,  144,  108,  109,  109,   86,   86,  345,  192,  345,
      247,   85,  180,  345,  145,  194,  345,  345,  146,  147,
      345,  345,   98,  148,   99,  108,  109,  109,  107,   92,
      149,   93,   76,  150,  191,  151,  345,  152,  345,  153,
      154,  345,  195,  345,  155,   98,   73,   99,   92,  198,
      345,  345,   72,  156,  156,  203,   93,  197,  345,   71,

      345,  157,   86,  105,  345,  273,  273,  345,  345,  345,
      345,  345,  345,  345,  158,  219,  219,  143,  159,  160,
      199,  196,  345,  161,  213,  200,  345,  345,  345,  345,
      162,  345,  345,  163,  345,  164,  345,  165,  345,  166,
       83,   83,   83,  345,  212,  208,  345,  201,  207,   84,
       84,   84,  169,  170,  202,  345,  171,  172,  210,  345,
      345,  345,  209,  345,  345,   84,   84,   84,   84,  169,
      170,  345,  345,  211,  345,  171,  204,  345,  345,  172,
      345,  216,  345,  217,  345,  223,  205,  206,  345,   84,
      214,  143,  143,  143,  345,  345,  172,  345,  215,  218,

      167,  167,  167,  345,  345,  224,  345,  224,  345,  345,
      225,  225,  225,  345,  226,  345,  226,  345,  172,  227,
      227,  227,  228,  228,  230,  230,  230,  172,  238,  345,
      345,  345,  233,  233,  345,  345,  240,  345,  234,  345,
      345,  239,  345,  345,  241,  345,  229,  231,  243,  172,
      232,  345,  345,  345,  345,  345,  235,  242,  236,  345,
      345,  345,  345,  345,  231,  229,  345,  345,  345,  232,
      248,  249,  252,  345,  345,  235,  244,  253,  345,  228,
      345,  345,  251,  236,  345,  345,  245,  246,  345,  237,
      250,  345,  255,  345,  345,  345,  345,  254,  256,  345,

      345,  345,  345,  345,  345,  257,  345,  345,  267,  259,
      345,  258,  345,  345,  345,  261,  345,  345,  345,  260,
      345,  345,  262,  345,  345,  271,  271,  143,  345,  345,
      268,  345,  265,  269,  345,  345,  276,  276,  276,  345,
      263,  345,  345,  264,  345,  345,  345,  266,  281,  281,
      345,  345,  345,  270,  225,  225,  225,  345,  345,  227,
      227,  227,  227,  227,  227,  283,   84,  345,  230,  230,
      230,  345,  282,  345,  345,  277,  345,  285,  278,  345,
      284,  279,  290,   84,  232,  345,  287,  345,  345,  345,
      345,  282,  277,  345,  345,  345,  345,  278,  279,  345,

      345,  345,  345,  232,  345,  281,  345,  345,  345,  286,
      345,  288,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  291,  143,  143,  143,  345,  345,  301,  345,  345,
      345,  293,  302,  292,  294,  345,  295,  298,  296,  300,
      345,  345,  345,  345,  297,  345,  303,  345,  299,  345,
      304,  345,  305,  345,  345,  345,  306,  345,  345,  345,
      172,  345,  345,  345,  276,  276,  276,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  308,  345,  345,
      171,  345,  172,  345,  345,  345,  345,  345,  345,  307,

      345,  345,  345,  345,  308,  345,  345,  345,  345,  171,
      345,  345,  345,  345,  310,  309,  313,  345,  345,  345,
      312,  311,  315,  314,  317,  319,  321,  345,  320,  345,
      345,  345,  324,  345,  345,  345,  345,  316,  327,  345,
      345,  318,  345,  326,  345,  345,  345,  345,  345,  322,
      325,  323,  345,  345,  345,  329,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  328,  345,  345,  345,
      345,  345,  345,  345,  345,  330,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  331,  345,  345,  332,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  337,  333,  345,
      334,  345,  345,  345,  335,  338,  345,  341,  345,  342,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  336,
      345,  345,  345,  340,  345,  345,  345,  339,  345,  345,
      345,  345,  343,  345,  345,  345,  345,  345,  345,  345,
      344,  345,  345,  345,   58,   58,   58,   58,   58,   58,
       58,   62,   62,   62,   62,   62,   62,   62,   67,   67,
       67,   67,   67,   67,   67,   84,   84,  345,  345,  345,
       84,  107,  107,  345,  107,  107,  107,   90,   90,   90,
      345,  345,   90,  182,  345,  345,  345,  182,  280,  345,

      345,  280,  280,    9,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345
    } ;

static const flex_int16_t yy_chk[1074] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    5,    6,   17,    5,    6,    3,    4,    7,    8,
       22,    7,    8,    5,    6,   11,   24,   11,   36,   17,
       25,   22,   25,   25,   25,   24,   24,   31,   31,   33,

       33,   37,   37,   37,  356,   90,    3,    4,    5,    6,
       27,   27,   42,   90,   46,   42,   27,   46,   27,   27,
       27,   37,   46,   37,   95,  140,   44,   27,   27,   27,
       27,   27,   95,  140,   27,   44,   27,   27,   40,   36,
       44,  177,   50,   27,   27,   27,   27,   27,   27,  177,
       40,   40,   52,   27,   47,   40,   43,   55,   70,  355,
       70,   27,   49,   43,   27,   53,   54,   27,   28,   43,
       28,   28,   28,   50,   43,   48,   45,   56,   45,   28,
       28,   28,   28,   28,   45,   56,  116,   45,  116,   40,
       28,   55,   28,   50,   47,   28,   28,   28,   28,   28,

       28,   52,   49,   52,   53,   47,   54,   48,   55,   51,
       72,   72,   72,   49,   48,  107,   53,   54,   84,   28,
       35,  354,   35,   35,   35,  353,   48,  247,   56,  119,
      111,   35,   35,   35,   35,   35,  173,   84,   87,   87,
       87,  234,  119,   51,   51,  156,  156,   35,   35,   35,
       35,   35,   35,   51,  114,   87,   51,  112,  173,   84,
       51,   96,   96,  234,   88,   88,  107,  108,  108,  108,
      111,   35,   41,  223,   41,   41,   41,   87,  113,  106,
       96,  111,  105,   41,   41,   41,   41,   41,   88,  108,
       88,   88,   89,   89,   89,   93,   93,  112,  114,   41,

       41,   41,   41,   41,   41,  114,  115,   88,  112,  118,
      120,  104,   89,  100,   89,   88,  113,   41,   88,   93,
       82,   88,   39,   41,   61,   91,   32,   91,   91,  113,
       91,   91,   91,   61,   61,   61,   91,  115,   93,  121,
      127,   61,   98,   98,   98,   99,   99,  117,  118,  124,
      193,   26,   93,  123,   61,  120,  129,  115,   61,   61,
      118,  120,   98,   61,   98,  109,  109,  109,  193,   99,
       61,   99,   21,   61,  117,   61,  122,   61,  125,   61,
       66,  126,  121,  135,   66,  109,   16,  109,   99,  124,
      121,  127,   15,   66,   66,  129,   99,  123,  117,   13,

      124,   66,   99,  231,  123,  221,  221,  129,  131,  134,
      128,  231,  132,    9,   66,  142,  142,  142,   66,   66,
      125,  122,    0,   66,  135,  126,    0,  122,    0,  125,
       66,  133,  126,   66,  135,   66,    0,   66,    0,   66,
       83,   83,   83,  130,  134,  132,  137,  128,  131,   83,
       83,   83,   83,   83,  128,  136,   83,   83,  133,  131,
      134,  128,  132,  132,  138,   83,   83,   83,   83,   83,
       83,    0,    0,  133,    0,   83,  130,  170,    0,   83,
        0,  137,  133,  137,  199,  167,  130,  130,  185,   83,
      136,  143,  143,  143,  130,    0,  170,  137,  136,  138,

      167,  167,  167,  186,  188,  169,  136,  169,  169,  187,
      169,  169,  169,    0,  172,  138,  172,  190,  170,  172,
      172,  172,  176,  176,  178,  178,  178,  169,  185,  179,
      189,  179,  182,  182,  191,  199,  187,  200,  182,  185,
      195,  186,  194,  192,  188,  198,  176,  179,  190,  169,
      179,  197,  196,  202,  186,  188,  182,  189,  182,  203,
      187,  205,  201,  204,  179,  176,  206,  207,  190,  179,
      194,  195,  198,  215,    0,  182,  191,  200,  210,  176,
      208,  189,  197,  182,  209,  191,  192,  192,  200,  182,
      196,  195,  203,  194,  192,  211,  198,  201,  204,  212,

      216,  213,  197,  196,  202,  205,  217,  214,  215,  207,
      203,  206,  205,  201,  204,  209,  218,  206,  207,  208,
      241,    0,  210,  243,  215,  219,  219,  219,  238,  210,
      216,  208,  213,  217,  244,  209,  224,  224,  224,  239,
      211,    0,  245,  212,  240,  248,  211,  214,  236,  236,
      212,  216,  213,  218,  225,  225,  225,  217,  214,  226,
      226,  226,  227,  227,  227,  238,  225,  218,  230,  230,
      230,  241,  236,  242,  243,  227,  246,  240,  227,  238,
      239,  230,  248,  225,  230,  244,  245,  249,  250,  251,
      239,  236,  227,  245,  253,  240,  248,  227,  230,  252,

      255,  256,  254,  230,  257,  236,  258,    0,  263,  242,
      259,  246,  268,  264,  262,    0,  260,    0,  261,    0,
      283,  266,  269,    0,  242,    0,  265,  246,    0,  267,
      286,  251,  271,  271,  271,  287,    0,  263,  249,  250,
      251,  254,  264,  252,  256,  253,  257,  260,  258,  262,
      252,  255,  256,  254,  259,  257,  265,  258,  261,  263,
      266,  259,  267,  268,  264,  262,  269,  260,  270,  261,
      280,  283,  266,  269,  276,  276,  276,  265,  284,  285,
      267,  286,  288,  289,  291,  290,  287,  276,  292,  295,
      276,  293,  280,  294,  297,  298,  299,  300,    0,  270,

        0,  303,  296,  304,  276,  301,  307,  309,  306,  276,
      311,  305,  313,  314,  285,  284,  290,  302,  315,  270,
      289,  288,  293,  291,  295,  298,  300,  310,  299,  284,
      285,  312,  303,  288,  289,  291,  290,  294,  309,  292,
      295,  296,  293,  306,  294,  297,  298,  299,  300,  301,
      305,  302,  303,  296,  304,  311,  301,  307,  309,  306,
      316,  311,  305,  313,  314,  317,  310,  318,  302,  315,
      319,  320,  321,  322,  323,  312,  324,  326,  310,  325,
      328,  327,  312,  330,  329,  333,    0,  334,  335,  332,
      336,  316,  338,  339,  317,  331,  340,  341,  342,    0,

      337,  343,  344,    0,    0,    0,    0,  328,  324,    0,
      325,  316,    0,    0,  326,  329,  317,  334,  318,  335,
        0,  319,  320,  321,  322,  323,    0,  324,  326,  327,
      325,  328,  327,  332,  330,  329,  333,  331,  334,  335,
      332,  336,  337,  338,  339,    0,  331,  340,  341,  342,
      343,  337,  343,  344,  346,  346,  346,  346,  346,  346,
      346,  347,  347,  347,  347,  347,  347,  347,  348,  348,
      348,  348,  348,  348,  348,  349,  349,    0,    0,    0,
      349,  350,  350,    0,  350,  350,  350,  351,  351,  351,
        0,    0,  351,  352,    0,    0,    0,  352,  357,    0,

        0,  357,  357,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 4 "lex.l"
   #include <stdlib.h>
   #include <stdio.h>
   #include "tokens-manual.h"
   #include <ctype.h>
   int get_line_info();
   int handle_error();
   int lineno;
     enum type {
        INT_SIGNED,
        INT_LONG,
        INT_LONGLONG,
        INT_UNSIGNED,
        INT_ULONG,
        INT_ULONGLONG,
        FLOATV,
        DOUBLEV,
        DOUBLE_LONG,
    };
       struct Num  {
    unsigned long long integer;
     long double fvalue;
     enum type type;
 
   };
   union yylval {
    char *string_literal;
    char charlit;
    struct Num num;
   
   };
 

   typedef union yylval YYSTYPE;
   YYSTYPE yylval;
    char filename_buf[256];
    char *filename_buf_ptr;
    int string_buf_len = 0;
        
#line 832 "lex.yy.c"

#line 834 "lex.yy.c"

#define INITIAL 0
#define charseq 1
#define str 2
#define filename 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 66 "lex.l"


#line 69 "lex.l"
    char string_buf[1024]; 
    char charvalue;
    char *string_buf_ptr;
    int char_count; 
    int count = 0;
#line 1063 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 346 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1004 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 74 "lex.l"
{ lineno++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 75 "lex.l"
{filename_buf_ptr = filename_buf; lineno = 0;  BEGIN(filename);  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 78 "lex.l"
{ 
    count++;
    if(count == 1) {
     *filename_buf_ptr = '\0'; printf("%s", filename_buf); 
    }
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 84 "lex.l"
{BEGIN(INITIAL); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "lex.l"
{ *filename_buf_ptr++ = yytext[0];  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "lex.l"
{ yylval.num.integer= atoi(yytext); yylval.num.type = INT_SIGNED; return NUMBER; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 90 "lex.l"
{ yylval.num.integer = atol(yytext); yylval.num.type =  INT_LONG; return NUMBER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 91 "lex.l"
{ yylval.num.integer = atoll(yytext); yylval.num.type = INT_LONGLONG; return NUMBER; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 92 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 10); yylval.num.type = INT_UNSIGNED; return NUMBER; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 93 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 10); yylval.num.type = INT_ULONG; return NUMBER; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 94 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 10); yylval.num.type = INT_ULONGLONG; return NUMBER; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 96 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 16);  yylval.num.type = INT_SIGNED; return NUMBER; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 97 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 16); yylval.num.type = INT_LONG; return NUMBER; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 98 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 16); yylval.num.type = INT_LONGLONG; return NUMBER; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 99 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 16); yylval.num.type = INT_UNSIGNED; return NUMBER; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 100 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 16); yylval.num.type = INT_ULONG; return NUMBER; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 101 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 16); yylval.num.type = INT_ULONGLONG; return NUMBER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 8); yylval.num.type = INT_SIGNED; return NUMBER; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 8); yylval.num.type = INT_LONG; return NUMBER; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 105 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 8); yylval.num.type = INT_LONGLONG; return NUMBER; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 106 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 8); yylval.num.type = INT_UNSIGNED; return NUMBER; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 107 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 8); yylval.num.type = INT_ULONG; return NUMBER; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 108 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 8); yylval.num.type =  INT_ULONGLONG; return NUMBER; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type = DOUBLEV;  return NUMBER;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type =  FLOATV; return NUMBER; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type =  DOUBLE_LONG; return NUMBER; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 114 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type =  DOUBLEV; return NUMBER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 115 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type = FLOATV; return NUMBER; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 116 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type = DOUBLE_LONG; return NUMBER; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 118 "lex.l"
{ yylval.num.fvalue = strtod(yytext, NULL); yylval.num.type = DOUBLEV; return NUMBER; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 119 "lex.l"
{ yylval.num.fvalue = strtold(yytext, NULL); yylval.num.type = FLOATV; return NUMBER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "lex.l"
{ yylval.num.fvalue = strtold(yytext, NULL); yylval.num.type = DOUBLE_LONG; return NUMBER; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "lex.l"
{   char_count = 0; BEGIN(charseq); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 123 "lex.l"
{ BEGIN(INITIAL); 
              if(char_count == 0) {
                fprintf(stderr, "Error multibyte char onfdasdfly first value was used \n");
              }  
              if(char_count > 1) {
                fprintf(stderr, "Error multibyte char only first value was used\n");
              }
              printf("%d", charvalue); //!!!!CHANGE TO RETURN AND SET YYVAL PROPERLY!!!
              yylval.charlit = charvalue;
              return CHARLIT;
              }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 134 "lex.l"
{
    int result;
    if (char_count == 0) {
    printf("GETTING OCTAL\n");
    sscanf(yytext + 1, "%o", &result);
    charvalue = result; 
    }
    char_count++;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 143 "lex.l"
{
    printf("invalid octal");
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 146 "lex.l"
{
   
      int result;
      yytext[0] = '0';
    if (char_count == 0) {
    printf("GETTING HEX\n");
    sscanf(yytext, "%x", &result);
    charvalue = result; 
    }
    char_count++;
    
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 158 "lex.l"
{  if(char_count == 0) charvalue = '\a'; char_count++; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 159 "lex.l"
{  if(char_count == 0) charvalue = '\b'; char_count++; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 160 "lex.l"
{  if(char_count == 0) charvalue = '\f'; char_count++; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 161 "lex.l"
{  if(char_count == 0) charvalue = '\r'; char_count++; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 162 "lex.l"
{  if(char_count == 0) charvalue = '\t'; char_count++; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 163 "lex.l"
{  if(char_count == 0) charvalue = '\v'; char_count++; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 164 "lex.l"
{  if(char_count == 0) charvalue = '\?'; char_count++; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 165 "lex.l"
{  if(char_count == 0) charvalue = '\''; char_count++; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 166 "lex.l"
{  if(char_count == 0) charvalue = '\n'; char_count++; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 167 "lex.l"
{  if(char_count == 0) charvalue = '\\'; char_count++; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 168 "lex.l"
{

    int result;
    if(char_count == 0) {
        printf("GETTING SC \n"); 
        charvalue = yytext[0];
    }
    char_count++;
}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 178 "lex.l"
{
    printf("Error invalid value in char seq");
}    
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 182 "lex.l"
{string_buf_ptr = string_buf; BEGIN(str);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 184 "lex.l"
{BEGIN(INITIAL); 
    *string_buf_ptr = '\0';
  printf("%s\n", string_buf);
  string_buf_len = string_buf_ptr - string_buf;
  yylval.string_literal = strdup(string_buf);
  return STRING;
   }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 191 "lex.l"
{
    int result;
    sscanf(yytext+1, "%o", &result);
    *string_buf_ptr++ = result;

}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 197 "lex.l"
{
    int result;
    yytext[0] = '0';
    printf("GETTING HEX\n");
    sscanf(yytext, "%x", &result);
    *string_buf_ptr++ = result;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 204 "lex.l"
{
    *string_buf_ptr++ = yytext[0];
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 208 "lex.l"
{  *string_buf_ptr++ = '\a';}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 209 "lex.l"
{   *string_buf_ptr++ = '\b';}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 210 "lex.l"
{   *string_buf_ptr++ = '\f'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 211 "lex.l"
{   *string_buf_ptr++ = '\r'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 212 "lex.l"
{   *string_buf_ptr++ = '\t'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 213 "lex.l"
{   *string_buf_ptr++ = '\v'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 214 "lex.l"
{   *string_buf_ptr++ = '\?'; printf("hi");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 215 "lex.l"
{   *string_buf_ptr++ = '\"'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 216 "lex.l"
{   *string_buf_ptr++ = '\''; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 217 "lex.l"
{   *string_buf_ptr++ = '\n'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 218 "lex.l"
{   *string_buf_ptr++ = '\\'; }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 220 "lex.l"
{
    printf("Error Invalid sequence in string\n");
}   
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 223 "lex.l"
{ ; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 224 "lex.l"
{ return AUTO; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 225 "lex.l"
{ return _BOOL; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 226 "lex.l"
{ return BREAK; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 227 "lex.l"
{ return CASE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 228 "lex.l"
{ return CHAR; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 229 "lex.l"
{ return _COMPLEX; } 
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 230 "lex.l"
{ return CONST;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 231 "lex.l"
{ return CONTINUE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 232 "lex.l"
{ return DEFAULT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 233 "lex.l"
{ return DO; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 234 "lex.l"
{ return DOUBLE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 235 "lex.l"
{ return ELSE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 236 "lex.l"
{ return ENUM; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 237 "lex.l"
{ return EXTERN; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 238 "lex.l"
{ return FLOAT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 239 "lex.l"
{ return FOR; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 240 "lex.l"
{ return GOTO; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 241 "lex.l"
{ return IF; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 242 "lex.l"
{ return _IMAGINARY; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 243 "lex.l"
{ return INLINE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 244 "lex.l"
{ return INT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 245 "lex.l"
{ return LONG; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 246 "lex.l"
{ return REGISTER; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 247 "lex.l"
{ return RESTRICT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 248 "lex.l"
{ return RETURN; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 249 "lex.l"
{ return SHORT; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 250 "lex.l"
{ return SIGNED; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 251 "lex.l"
{ return SIZEOF; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 254 "lex.l"
{ return STATIC; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 255 "lex.l"
{ return STRUCT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 256 "lex.l"
{ return SWITCH; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 257 "lex.l"
{ return TYPEDEF; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 258 "lex.l"
{ return UNION; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 259 "lex.l"
{ return UNSIGNED; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 260 "lex.l"
{ return VOID; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 261 "lex.l"
{ return VOLATILE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 262 "lex.l"
{ return WHILE; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 264 "lex.l"
{ return INDSEL;  } 
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 265 "lex.l"
{ return PLUSPLUS; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 266 "lex.l"
{ return MINUSMINUS; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 267 "lex.l"
{ return SHL; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 268 "lex.l"
{ return SHR; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 269 "lex.l"
{ return LTEQ; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 270 "lex.l"
{ return GTEQ; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 271 "lex.l"
{ return EQEQ; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 272 "lex.l"
{ return NOTEQ; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 273 "lex.l"
{ return LOGAND; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 274 "lex.l"
{ return LOGOR; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 275 "lex.l"
{ return ELLIPSIS; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 276 "lex.l"
{ return TIMESEQ; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 277 "lex.l"
{ return DIVEQ; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 278 "lex.l"
{ return MODEQ; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 279 "lex.l"
{ return PLUSEQ; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 280 "lex.l"
{ return MINUSEQ; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 281 "lex.l"
{ return SHLEQ; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 282 "lex.l"
{ return SHREQ; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 283 "lex.l"
{ return ANDEQ; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 284 "lex.l"
{ return OREQ; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 285 "lex.l"
{ return XOREQ; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 288 "lex.l"
{ return '!'; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 289 "lex.l"
{ return '^'; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 290 "lex.l"
{ return '&'; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 291 "lex.l"
{ return '*'; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 292 "lex.l"
{ return '-'; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 293 "lex.l"
{ return '+'; }              
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 294 "lex.l"
{ return '='; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 295 "lex.l"
{ return '~'; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 296 "lex.l"
{ return '|'; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 297 "lex.l"
{ return '.'; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 298 "lex.l"
{ return '<'; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 299 "lex.l"
{ return '>'; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 300 "lex.l"
{ return '/'; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 301 "lex.l"
{ return '?'; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 302 "lex.l"
{ return '('; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 303 "lex.l"
{ return ')'; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 304 "lex.l"
{ return '['; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 305 "lex.l"
{ return ']'; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 306 "lex.l"
{ return ','; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 307 "lex.l"
{ return ';'; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 308 "lex.l"
{ return ':'; }     
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 310 "lex.l"
{ yylval.string_literal = strdup(yytext); return IDENT; /* put somewhere */ }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 311 "lex.l"
{ fprintf(stderr, "Error unrecognized token : %s\n", yytext); }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 312 "lex.l"
ECHO;
	YY_BREAK
#line 1941 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(charseq):
case YY_STATE_EOF(str):
case YY_STATE_EOF(filename):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 346 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 346 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 345);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 312 "lex.l"

int get_line_info(){
    printf("got here at least");
    lineno = 0;
    
}
// print filename, line number and the incorrect token
// int handle_error(){
//     fprintf(stderr, "Error in file %s on line number %d: %s\n", filename, lineno, yytext);
// }
void charhelper(char val) {
    switch(val) {
        case '\a': printf("\a"); break;
        case '\b': printf("\\b"); break;
        case '\f': printf("\\f"); break;
        case '\n': printf("\\n"); break;
        case '\r': printf("\\r"); break;
        case '\t': printf("\\t"); break;
        case '\v': printf("\\v"); break;
        default: printf("\\%03o", val);
    }
}
int yywrap() {}
int main() {
    int t;
while(t = yylex())  {
   printf("%s \t\t %d \t\t",filename_buf, lineno);  
    switch(t) 
    {
        case AUTO:               printf("AUTO\n"); break;
        case _BOOL:             printf("_BOOL\n"); break;
        case BREAK:             printf("BREAK\n"); break;
        case CASE:              printf("CASE\n"); break;
        case CHAR:              printf("CHAR\n"); break;
        case _COMPLEX:          printf("_COMPLEX\n"); break;
        case CONST:             printf("CONST\n"); break;
        case CONTINUE:          printf("CONTINUE\n"); break;
        case DEFAULT:           printf("DEFAULT\n"); break;
        case DO:                printf("DO\n"); break;
        case DOUBLE:            printf("DOUBLE\n"); break;
        case ELSE:              printf("ELSE\n"); break;
        case ENUM:              printf("ENUM\n"); break;
        case EXTERN:            printf("EXTERN\n"); break;
        case FLOAT:             printf("Float\n"); break;
        case FOR:               printf("For\n"); break;
        case GOTO:              printf("Goto\n"); break;
        case IF:                printf("If\n"); break;
        case _IMAGINARY:        printf("_IMAGINARY\n"); break;
        case INLINE:            printf("Inline\n"); break;
        case INT:               printf("Int\n"); break;
        case LONG:              printf("Long\n"); break;
        case REGISTER:          printf("Register\n"); break;
        case RESTRICT:          printf("Restrict\n"); break;
        case RETURN:            printf("Return\n"); break;
        case SHORT:             printf("Short\n"); break;
        case SIGNED:            printf("Signed\n"); break;
        case SIZEOF:            printf("Sizeof\n"); break;
        case STATIC:            printf("Static\n"); break;
        case STRUCT:            printf("Struct\n"); break;
        case SWITCH:            printf("Switch\n"); break;
        case TYPEDEF:           printf("Typedef\n"); break;
        case UNION:             printf("Union\n"); break;
        case UNSIGNED:          printf("Unsigned\n"); break;
        case VOID:              printf("Void\n"); break;
        case VOLATILE:          printf("Volatile\n"); break;
        case WHILE:             printf("While\n"); break;
        case INDSEL:            printf("->\n"); break;
        case PLUSPLUS:          printf("++\n"); break;
        case MINUSMINUS:        printf("--\n"); break;
        case SHL:               printf("<<\n"); break;
        case SHR:               printf(">>\n"); break;
        case LTEQ:              printf("<=\n"); break;
        case GTEQ:              printf(">=\n"); break;
        case EQEQ:              printf("==\n"); break;
        case NOTEQ:             printf("!=\n"); break;
        case LOGAND:            printf("&&\n"); break;
        case LOGOR:             printf("||\n"); break;
        case ELLIPSIS:          printf("ELIPSIS\n"); break;
        case TIMESEQ:           printf("*=\n"); break;
        case DIVEQ:             printf("/=\n"); break;
        case MODEQ:             printf("\n"); break;
        case PLUSEQ:            printf("+=\n"); break;
        case MINUSEQ:           printf("-=\n"); break;
        case SHLEQ:             printf("<<=\n"); break;
        case SHREQ:             printf(">>=\n"); break;
        case ANDEQ:             printf("&=\n"); break;
        case OREQ:              printf("|=\n"); break;
        case XOREQ:             printf("^=\n"); break;
        case '!':               printf("!\n"); break;
        case '^':               printf("^\n"); break;
        case '&':               printf("&\n"); break;
        case '*':               printf("*\n"); break;
        case '-':               printf("-\n"); break;
        case '+':               printf("+\n"); break;
        case '=':               printf("=\n"); break;
        case '~':               printf("~\n"); break;
        case '|':               printf("|\n"); break;
        case '.':               printf(".\n"); break;
        case '<':               printf("<\n"); break;
        case '>':               printf(">\n"); break;
        case '/':               printf("/\n"); break;
        case '?':               printf("?\n"); break;
        case '(':               printf("(\n"); break;
        case ')':               printf(")\n"); break;
        case '[':               printf("[\n"); break;
        case ']':               printf("]\n"); break;
        case ',':               printf(",\n"); break;
        case ';':               printf(";\n"); break;
        case ':':               printf(":\n"); break;
        case IDENT:             printf("IDENT    %s\n", yylval.string_literal); break;
        case NUMBER:  printf("NUMBER:  "); switch(yylval.num.type) {
            case INT_SIGNED: printf(" \t INTEGER %d  \t INT\n", yylval.num.integer); break;
            case INT_LONG: printf(" \t INTEGER %d \t LONG INT\n", yylval.num.integer ); break;
            case INT_LONGLONG: printf(" \t INTEGER %d \t LONG LONG INT\n", yylval.num.integer ); break;
            case INT_ULONG: printf(" \t INTEGER %d \t UNSIGNED LONG INT\n", yylval.num.integer ); break;
            case INT_ULONGLONG: printf(" \t INTEGER %d \t UNSIGNED LONG LONG INT\n", yylval.num.integer ); break;
            case FLOATV: printf("\t REAL \t %Lf \t FLOAT\n", yylval.num.fvalue); break;
            case DOUBLEV: printf("\t REAL \t %Lf \t DOUBLE\n", yylval.num.fvalue); break;
            case DOUBLE_LONG: printf("\t REAL \t %Lf \t LONG DOUBLE\n", yylval.num.fvalue); break;

        } break;
        case CHARLIT: {
          if(isprint(yylval.charlit)) {
            if(yylval.charlit == '\'' || yylval.charlit == '\'' || yylval.charlit == '\"' || yylval.charlit == '\\' ) {
                printf("\\%c\n", yylval.charlit);
            } else {
            printf("%c\n", yylval.charlit); 
            }
          } else {
            charhelper(yylval.charlit);
            printf("\n");
          }
            
        } break;

       case STRING: { 
        printf("\t STRING \t");
        for(int i = 0; i < string_buf_len; i++) {
                if(isprint(yylval.string_literal[i])) {
            if(yylval.string_literal[i]== '\'' || yylval.string_literal[i] == '\'' || yylval.string_literal[i] == '\"' || yylval.string_literal[i] == '\\') {
                printf("\\%c", yylval.string_literal[i]);
            } else {
            printf("%c", yylval.string_literal[i]); 
            }
          } else {
            charhelper(yylval.string_literal[i]);
        
          }
              
        }
        printf("\n");
       } break;



        //we have to add the rest 
        default: printf("sussy\n");
    }
  
    
}

}

