
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 143
#define YY_END_OF_BUFFER 144
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[327] =
    {   0,
        0,    0,   39,   39,   56,   56,  144,  142,   60,    1,
      120,   45,  142,  122,   29,  134,  135,  123,  125,  138,
      124,  129,  132,   14,    2,  140,  139,  130,  126,  131,
      133,  142,  142,  136,  137,  121,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  128,  127,   43,   44,   30,   39,   49,  143,
       46,   56,   60,  106,  112,  107,  117,  110,   99,  113,
      100,  114,   98,    0,   20,    0,  111,   16,   20,    0,
       14,    0,    0,   15,   17,    0,   16,    4,    2,    2,
        3,    5,    4,  101,  103,  105,  104,  102,    0,  141,

      141,  119,  141,  141,  141,  141,  141,  141,  141,  141,
      141,   70,  141,  141,  141,  141,  141,  141,   78,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      118,  108,   40,   31,   42,   33,   34,   35,   41,   36,
       37,   38,    0,   57,   47,   59,   50,   51,   52,   58,
       53,   54,   55,    0,  109,    0,   21,   22,    0,   20,
        0,   23,   19,   18,    8,    7,    6,  115,  116,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,   76,  141,  141,   81,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,

      141,  141,  141,   31,   32,   47,   48,    0,   20,    0,
       26,   23,   24,   25,   10,    0,    9,   11,    8,  141,
      141,  141,   61,  141,   64,   65,  141,  141,  141,  141,
       72,   73,  141,  141,   77,  141,   82,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,   95,
      141,  141,   31,   32,   47,   48,   20,   27,   28,   24,
        0,   13,   12,   62,  141,  141,   63,   67,  141,  141,
      141,  141,   75,  141,  141,  141,  141,   86,  141,  141,
      141,  141,  141,  141,   93,  141,  141,   97,   21,  141,
      141,  141,  141,   71,   74,   80,  141,  141,   85,   87,

       88,   89,   90,   91,  141,  141,  141,  141,  141,  141,
       69,  141,  141,   92,  141,  141,   66,  141,   68,   83,
       84,   94,   96,  141,   79,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   26,   29,   30,
       31,   31,   32,   31,   31,   33,   31,   31,   31,   34,
       31,   31,   31,   31,   35,   31,   31,   36,   31,   31,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   31,   51,   52,   53,   54,
       55,   56,   31,   57,   58,   59,   60,   61,   62,   63,
       64,   65,    1,   66,    1,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    1,    3,    3,    3,    1,
        1,    1,    4,    1,    1,    3,    3,    3,    3,    3,
        5,    5,    5,    6,    5,    5,    1,    1,    1,    1,
        5,    3,    3,    3,    3,    3,    3,    5,    5,    5,
        5,    5,    5,    5,    5,    6,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    7,    1
    } ;

static const flex_int16_t yy_base[338] =
    {   0,
        0,    0,   65,   66,   67,   72,  438,  935,   76,   78,
      414,  935,  412,   64,  935,  935,  935,  411,   70,  935,
       62,   73,  385,  102,  160,  935,  935,   61,  331,   71,
      935,  212,   74,  935,  935,  325,   86,  264,   39,   67,
       79,  101,   81,  108,  144,  128,  135,  184,   92,  142,
      145,  169,   85,  935,  935,  935,  935,  323,  935,  935,
      935,  382,   95,  935,  935,  935,  935,  935,  935,  935,
      935,  935,  935,  322,  429,  158,  935,  935,  230,  251,
       79,  157,  300,  935,  292,    0,  194,  935,  148,    0,
      935,  294,  198,  310,  935,  935,  935,  266,  248,  172,

      156,  935,  170,  222,  209,  201,  230,   66,  229,  272,
      168,  269,  270,  283,  298,  250,  285,  317,  284,  319,
      337,  347,  324,  307,  332,  338,  341,  344,  366,  378,
      935,  238,  935,  234,  935,  935,  935,  935,  935,  935,
      935,  935,    0,  935,  255,  935,  935,  935,  935,  935,
      935,  935,  935,    0,  935,  465,  377,  935,  474,  163,
      350,  475,  935,  935,  491,  935,  935,  935,  935,  360,
      348,  412,  394,  452,  404,  446,  438,  370,  487,  483,
      454,  494,  475,  330,  495,  402,  449,  496,  498,  499,
      508,  510,  516,  513,  518,  520,  519,  517,  532,  522,

      524,  531,  523,  303,    0,  404,    0,  537,  574,  577,
      582,  588,  408,  935,  935,  568,  935,  599,    0,  589,
      596,  595,  450,  598,  551,  556,  601,  604,  163,  611,
      608,  610,  612,  613,  615,  621,  616,  622,  627,  629,
      624,  643,  630,  641,  653,  656,  658,  638,  651,  632,
      635,  687,  935,  935,  935,  935,  693,  935,  935,  935,
      671,  935,  935,  642,  691,  698,  699,  700,  701,  706,
      703,  705,  710,  714,  715,  713,  716,  717,  723,  726,
      731,  719,  735,  741,  720,  736,  727,  722,  935,  776,
      746,  739,  737,  729,  732,  747,  779,  789,  791,  793,

      794,  795,  796,  799,  800,  802,  801,  806,  804,  805,
      808,  816,  817,  809,  811,  812,  813,  823,  815,  819,
      820,  821,  822,  826,  825,  935,  892,  899,  905,  911,
      917,  922,  179,  173,  103,   99,  927
    } ;

static const flex_int16_t yy_def[338] =
    {   0,
      326,    1,  327,  327,  328,  328,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  329,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  330,  330,  326,  326,  326,  330,  330,   38,   38,
       38,   38,   38,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  331,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  329,  326,  326,   75,  331,
       24,  331,  331,  326,  326,  332,  331,  326,   25,   25,
      326,  326,  331,  326,  326,  326,  326,  326,  329,   38,

      330,  326,  330,  330,  330,  330,  330,   38,  330,  330,
       38,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      326,  331,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  333,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  334,  326,  329,  329,  326,  326,   79,
      326,   83,  326,  326,  332,  326,  326,  326,  326,  330,
      330,  330,  330,  330,  330,  330,  330,   38,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  326,  335,  326,  336,  326,   75,  326,
      326,  326,  331,  326,  326,  337,  326,  326,  165,  330,
      330,  330,  330,  330,  330,  330,  330,  330,   38,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  326,  326,  326,  326,  326,  326,  326,  326,
      337,  326,  326,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  326,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,    0,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326
    } ;

static const flex_int16_t yy_nxt[1003] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   25,   26,
       27,   28,   29,   30,   31,   32,   32,   32,   32,   32,
       33,   33,   33,   33,   33,   33,   34,    8,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   33,   45,
       33,   46,   33,   33,   33,   33,   47,   48,   49,   50,
       51,   52,   33,   33,   33,   53,   54,   56,   56,   60,
       66,   61,   57,   57,   60,   71,   61,   63,   63,   63,
       63,   69,   94,   95,   72,   73,   67,   74,  326,   75,
       75,   75,   70,   97,   98,  107,   63,   63,  101,   99,

      326,  256,   58,   58,   62,  254,  326,  131,  108,   62,
       78,   78,  103,  104,  326,  109,   79,  105,   80,   81,
       80,  110,  326,  175,  111,  101,  101,   82,   82,   82,
       83,   82,  116,  112,   84,  117,   85,   86,  101,  326,
      101,  326,  326,   82,   82,   82,   82,   83,   82,  326,
      132,  326,  113,   84,  114,  127,  326,  326,  326,  326,
      101,   85,  118,  115,   86,   89,   89,   87,   88,   88,
      326,   99,  326,  326,   79,  207,   89,   90,   90,  326,
      122,  205,  121,  326,  326,   82,   82,   82,   83,   82,
      119,  159,   91,  326,   92,  128,  159,  120,  326,  129,

      326,   82,   82,   82,   82,   83,   82,  326,   99,  326,
      326,   91,   99,  159,  178,  326,  326,  130,  159,   92,
      326,  326,  270,  326,  170,   93,   99,  101,  100,  100,
      100,  101,  123,  124,  326,  326,  326,  100,  100,  100,
      100,  100,  125,  326,  326,  126,  160,  160,  160,  326,
      204,  204,   99,  100,  100,  100,  100,  100,  100,  173,
      326,  172,  326,  326,  326,   79,  326,   80,   80,   80,
      176,  206,  206,  326,  326,  174,  171,   82,   99,   83,
      100,  100,  100,  326,  326,  326,  326,  326,  169,  100,
      100,  100,  100,  100,  326,  326,   83,  326,  326,  326,

      163,  163,  166,  166,  183,  100,  100,  100,  100,  100,
      100,  161,  326,  161,   99,  326,  162,  162,  162,  253,
      253,  326,  326,  106,  164,  177,  167,  180,  179,   82,
      133,  326,  168,  326,  326,  326,  155,  326,  326,  134,
      134,  184,  181,  164,  326,  167,  326,  102,  326,  326,
      326,  326,  326,   96,  193,  326,  182,  163,  326,  166,
      135,  326,  326,  326,  136,  137,  212,  212,  212,  138,
      186,  194,  326,  195,  326,  185,  139,  187,  192,  140,
      326,  141,  326,  142,  326,  143,  144,  197,  196,  326,
      188,  326,  326,  199,  189,  326,  198,  326,  145,  145,

      221,  200,  326,  326,  190,  191,  326,   77,  326,  326,
      159,  229,  326,  326,  220,  201,  326,  202,  326,  146,
      255,  255,   99,  147,  148,  326,  326,  203,  149,  101,
      326,  326,  159,   68,   65,  150,   64,  326,  151,  326,
      152,  326,  153,  326,  154,   75,   75,   75,  223,  225,
      326,  236,  326,  222,   76,   76,   76,  156,  157,  326,
      326,  158,  159,  326,  326,  326,  326,  326,  326,  326,
       76,   76,   76,   76,  156,  157,  208,  326,  208,  326,
      158,  209,  209,  209,  159,  210,  326,  210,  326,  326,
      211,  211,  211,  224,   76,  227,  228,  326,  159,  215,

      215,  326,  226,  326,  213,  216,  232,  214,  326,  326,
      326,  326,  326,  326,  326,  326,  234,  326,  326,  326,
      159,  213,  326,  217,  326,  218,  214,  326,  231,  230,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  233,
      326,  326,  217,  237,  326,  326,  326,  238,  326,  235,
      218,  326,  326,  257,  257,  257,  219,  239,  243,  326,
      326,  326,  247,  326,  326,  326,  241,  240,  250,  242,
      326,  249,  251,  326,  252,  326,  244,  246,  326,  245,
      326,  326,  326,  326,  326,  326,  248,  326,  326,  326,
      209,  209,  209,  211,  211,  211,  326,  326,  211,  211,

      211,  159,   76,  326,  212,  212,  212,  262,  262,  326,
      326,  258,  326,  326,  259,  326,  326,  260,  326,   76,
      214,  326,  326,  159,  326,  326,  326,  326,  258,  326,
      326,  263,  326,  259,  260,  326,  326,  326,  326,  214,
      264,  326,  266,  326,  326,  326,  326,  326,  267,  326,
      263,  265,  326,  269,  326,  326,  326,  326,  326,  268,
      326,  326,  271,  326,  262,  326,  326,  326,  272,  326,
      326,  273,  326,  326,  274,  326,  326,  326,  326,  275,
      326,  326,  278,  276,  280,  277,  326,  326,  279,  326,
      281,  285,  326,  287,  326,  326,  282,  326,  286,  283,

      326,  326,  284,  326,  159,  326,  326,  326,  326,  257,
      257,  257,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  289,  326,  326,  158,  159,  326,  326,  326,
      326,  326,  288,  326,  326,  326,  326,  326,  326,  289,
      326,  326,  290,  326,  158,  326,  326,  291,  294,  326,
      326,  326,  326,  326,  292,  326,  326,  293,  295,  296,
      326,  326,  298,  326,  326,  326,  326,  300,  326,  299,
      326,  326,  301,  297,  302,  326,  307,  303,  326,  326,
      326,  326,  326,  304,  326,  326,  305,  326,  326,  306,
      326,  326,  326,  326,  326,  311,  326,  326,  310,  309,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  308,  326,  326,  312,  326,  326,  326,  326,  326,
      326,  326,  313,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  318,  314,  315,  326,  326,
      319,  326,  316,  326,  326,  322,  326,  323,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  317,  326,
      326,  326,  320,  326,  326,  321,  326,  326,  326,  324,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  325,
      326,  326,   55,   55,   55,   55,   55,   55,   55,   59,

       59,   59,   59,   59,   59,   59,   76,   76,  326,  326,
      326,   76,  101,  101,  326,  101,  101,  101,   82,   82,
       82,  326,  326,   82,  165,  326,  326,  326,  165,  261,
      326,  326,  261,  261,    7,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326
    } ;

static const flex_int16_t yy_chk[1003] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
       14,    5,    3,    4,    6,   21,    6,    9,    9,   10,
       10,   19,   28,   28,   21,   21,   14,   22,   33,   22,
       22,   22,   19,   30,   30,   39,   63,   63,   39,   53,

       37,  336,    3,    4,    5,  335,   49,   53,   40,    6,
       24,   24,   37,   37,   81,   40,   24,   37,   24,   24,
       24,   40,   44,  108,   41,  108,   40,   24,   24,   24,
       24,   24,   43,   41,   24,   43,   24,   24,   41,   33,
       43,   81,   46,   24,   24,   24,   24,   24,   24,   47,
       53,   37,   42,   24,   42,   49,   50,   49,   45,   51,
       42,   24,   44,   42,   24,   89,   89,   24,   25,   25,
      101,   82,   76,   44,   25,  334,   25,   25,   25,   82,
       47,  333,   46,   52,  103,   25,   25,   25,   25,   25,
       45,   76,   25,   46,   25,   50,  160,   45,   48,   51,

       47,   25,   25,   25,   25,   25,   25,   50,   87,   45,
       51,   25,   93,   76,  111,  106,   87,   52,  160,   25,
       93,  101,  229,  105,  103,   25,   32,  111,   32,   32,
       32,  100,   48,   48,   52,  103,  104,   32,   32,   32,
       32,   32,   48,  109,  107,   48,   79,   79,   79,   48,
      134,  134,  132,   32,   32,   32,   32,   32,   32,  106,
      132,  105,   99,   79,  116,   80,  106,   80,   80,   80,
      109,  145,  145,   80,  105,  107,  104,   32,   38,   80,
       38,   38,   38,  112,  113,   79,  110,  104,   98,   38,
       38,   38,   38,   38,  109,  107,   80,  114,  119,  117,

       85,   85,   92,   92,  116,   38,   38,   38,   38,   38,
       38,   83,  115,   83,   83,  116,   83,   83,   83,  204,
      204,  124,   83,   38,   85,  110,   92,  113,  112,   38,
       58,  118,   94,  120,  112,  113,   74,  110,  123,   58,
       58,  117,  114,   85,  184,   92,  125,   36,  114,  119,
      117,  121,  126,   29,  124,  127,  115,   85,  128,   92,
       58,  122,  171,  115,   58,   58,  161,  161,  161,   58,
      120,  124,  124,  125,  170,  118,   58,  120,  123,   58,
      129,   58,  118,   58,  120,   58,   62,  126,  125,  123,
      121,  157,  130,  128,  122,  184,  127,  125,   62,   62,

      171,  128,  121,  126,  122,  122,  127,   23,  173,  128,
      157,  178,  122,  171,  170,  129,  186,  129,  175,   62,
      206,  206,  213,   62,   62,  170,  172,  130,   62,  178,
      213,  129,  157,   18,   13,   62,   11,    7,   62,    0,
       62,    0,   62,  130,   62,   75,   75,   75,  173,  175,
        0,  186,  177,  172,   75,   75,   75,   75,   75,  173,
      176,   75,   75,  187,  223,    0,  174,  186,  181,  175,
       75,   75,   75,   75,   75,   75,  156,  172,  156,  156,
       75,  156,  156,  156,   75,  159,  162,  159,  162,  183,
      159,  159,  159,  174,   75,  177,  177,  180,  156,  165,

      165,  179,  176,  177,  162,  165,  181,  162,  182,  185,
      188,  176,  189,  190,  187,  223,  183,  174,    0,  181,
      156,  162,  191,  165,  192,  165,  162,  194,  180,  179,
      193,  198,  195,  197,  196,    0,  200,  203,  201,  182,
      183,    0,  165,  188,    0,  202,  199,  189,  180,  185,
      165,    0,  179,  208,  208,  208,  165,  190,  194,  182,
      185,  188,  198,  189,  190,  225,  192,  191,  201,  193,
      226,  200,  202,  191,  203,  192,  195,  197,  194,  196,
        0,  193,  198,  195,  197,  196,  199,  200,  203,  201,
      209,  209,  209,  210,  210,  210,  202,  199,  211,  211,

      211,  216,  209,  220,  212,  212,  212,  218,  218,  222,
      221,  211,  224,    0,  211,  227,  225,  212,  228,  209,
      212,  226,  231,  216,  232,  230,  233,  234,  211,  235,
      237,  218,    0,  211,  212,  236,  238,    0,  241,  212,
      220,  239,  222,  240,  243,    0,  250,    0,  224,  251,
      218,  221,  248,  228,  220,  244,  264,  242,    0,  227,
      222,  221,  230,  224,  218,  249,  227,  245,  233,  228,
      246,  234,  247,  231,  236,  232,  230,  233,  234,  238,
      235,  237,  241,  239,  243,  240,  236,  238,  242,  241,
      244,  248,  239,  251,  240,  243,  245,  250,  249,  246,

      251,  252,  247,  248,  261,  265,  244,  264,  242,  257,
      257,  257,  266,  267,  268,  269,  249,  271,  245,  272,
      270,  246,  257,  247,  273,  257,  261,  276,  274,  275,
      277,  278,  252,  282,  285,    0,  288,  279,    0,  257,
      280,  287,  265,  294,  257,  281,  295,  266,  271,  283,
      286,  293,  252,  292,  269,  284,  265,  270,  272,  274,
      291,  296,  276,  266,  267,  268,  269,  279,  271,  277,
      272,  270,  280,  275,  281,  273,  287,  282,  276,  274,
      275,  277,  278,  283,  282,  285,  284,  288,  279,  286,
      290,  280,  287,  297,  294,  293,  281,  295,  292,  291,

      283,  286,  293,  298,  292,  299,  284,  300,  301,  302,
      303,  291,  296,  304,  305,  307,  306,    0,  309,  310,
      308,  290,  311,  314,  297,  315,  316,  317,    0,  319,
      312,  313,  298,  320,  321,  322,  323,  318,    0,  325,
      324,  290,    0,    0,  297,  309,  305,  306,    0,    0,
      310,    0,  307,    0,  298,  315,  299,  316,  300,  301,
      302,  303,    0,    0,  304,  305,  307,  306,  308,  309,
      310,  308,  312,  311,  314,  313,  315,  316,  317,  318,
      319,  312,  313,    0,  320,  321,  322,  323,  318,  324,
      325,  324,  327,  327,  327,  327,  327,  327,  327,  328,

      328,  328,  328,  328,  328,  328,  329,  329,    0,    0,
        0,  329,  330,  330,    0,  330,  330,  330,  331,  331,
      331,    0,    0,  331,  332,    0,    0,    0,  332,  337,
        0,    0,  337,  337,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 4 "lex.l"
   #include "tokens-manual.h"
   int lineno;
   struct yylval {
    char *string_literal;
    int integer;
    char *type;
    double finteger;
   };
   struct yylval yylval;
        
        
#line 785 "lex.yy.c"

#line 787 "lex.yy.c"

#define INITIAL 0
#define charseq 1
#define str 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "lex.l"

#line 40 "lex.l"
    char string_buf[1024]; 
    char charvalue;
    char *string_buf_ptr;
    int char_count; 
    

#line 1015 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 327 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 935 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 46 "lex.l"
{ lineno++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int"; return NUMBER; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, long"; return NUMBER; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, longlong"; return NUMBER; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, unsigned"; return NUMBER; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, unsigned long"; return NUMBER; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, unsigned longlong"; return NUMBER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "lex.l"
{ yylval.integer = atoi(yytext);  yylval.type = "int"; return NUMBER; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, long"; return NUMBER; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, longlong"; return NUMBER; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, unsigned"; return NUMBER; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, unsigned long"; return NUMBER; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, unsigned longlong"; return NUMBER; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 61 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int"; return NUMBER; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, long"; return NUMBER; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, longlong"; return NUMBER; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, unsigned"; return NUMBER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, unsigned long"; return NUMBER; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "lex.l"
{ yylval.integer = atoi(yytext); yylval.type = "int, unsigned longlong"; return NUMBER; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 68 "lex.l"
{ yylval.finteger = atof(yytext); yylval.type = "int, unsigned longlong"; return NUMBER; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "lex.l"
{ yylval.finteger = atof(yytext); yylval.type = "int, unsigned longlong"; return NUMBER; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 70 "lex.l"
{ yylval.finteger = atof(yytext); yylval.type = "int, unsigned longlong"; return NUMBER; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "lex.l"
{ yylval.finteger = atof(yytext); yylval.type = "int, unsigned longlong"; return NUMBER; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "lex.l"
{ yylval.finteger = atof(yytext); yylval.type = "int, unsigned longlong"; return NUMBER; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "lex.l"
{ yylval.finteger = atof(yytext); yylval.type = "int, unsigned longlong"; return NUMBER; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "lex.l"

	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "lex.l"

	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "lex.l"

	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "lex.l"
{   char_count = 0; BEGIN(charseq); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "lex.l"
{ BEGIN(INITIAL); 
              if(char_count != 1) {
                fprintf(stderr, "Error multibyte char only first value was used \n");
              }  
              printf("%c", charvalue); 
              }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 87 "lex.l"
{
    int result;
    if (char_count == 0) {
    printf("GETTING OCTAL\n");
    sscanf(yytext + 1, "%o", &result);
    charvalue = result; 
    }
    char_count++;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "lex.l"
{
      int result;
      yytext[0] = '0';
    if (char_count == 0) {
    printf("GETTING HEX\n");
    sscanf(yytext, "%x", &result);
    charvalue = result; 
    }
    char_count++;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 106 "lex.l"
{  if(char_count == 0) charvalue = '\a'; char_count++; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 107 "lex.l"
{  if(char_count == 0) charvalue = '\b'; char_count++; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 108 "lex.l"
{  if(char_count == 0) charvalue = '\f'; char_count++; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 109 "lex.l"
{  if(char_count == 0) charvalue = '\r'; char_count++; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 110 "lex.l"
{  if(char_count == 0) charvalue = '\t'; char_count++; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 111 "lex.l"
{  if(char_count == 0) charvalue = '\v'; char_count++; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 112 "lex.l"
{  if(char_count == 0) charvalue = '\?'; char_count++; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 113 "lex.l"
{  if(char_count == 0) charvalue = '\''; char_count++; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 114 "lex.l"
{  if(char_count == 0) charvalue = '\n'; char_count++; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 115 "lex.l"
{  if(char_count == 0) charvalue = '\\'; char_count++; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 116 "lex.l"
{
    int result;
    if(char_count == 0) {
        printf("GETTING SC \n"); 
        charvalue = yytext[0];
    }
    char_count++;
}
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 125 "lex.l"
{
    printf("Error invalid value in char seq");
}    
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 129 "lex.l"
{string_buf_ptr = string_buf; BEGIN(str);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 131 "lex.l"
{BEGIN(INITIAL); 
    *string_buf_ptr = '\0';
    printf("%s\n", string_buf); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 134 "lex.l"
{
    int result;
    sscanf(yytext+1, "%o", &result);
    *string_buf_ptr++ = result;

}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 140 "lex.l"
{
    int result;
    yytext[0] = '0';
    printf("GETTING HEX\n");
    sscanf(yytext, "%x", &result);
    *string_buf_ptr++ = result;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 147 "lex.l"
{
    *string_buf_ptr++ = yytext[0];
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 150 "lex.l"
{  *string_buf_ptr++ = '\a';}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 151 "lex.l"
{   *string_buf_ptr++ = '\b';}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 152 "lex.l"
{   *string_buf_ptr++ = '\f'; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 153 "lex.l"
{   *string_buf_ptr++ = '\r'; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 154 "lex.l"
{   *string_buf_ptr++ = '\t'; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 155 "lex.l"
{   *string_buf_ptr++ = '\v'; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 156 "lex.l"
{   *string_buf_ptr++ = '\?'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 157 "lex.l"
{   *string_buf_ptr++ = '\"'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 158 "lex.l"
{   *string_buf_ptr++ = '\n'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 159 "lex.l"
{   *string_buf_ptr++ = '\\'; }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 162 "lex.l"
{ printf("white space"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 163 "lex.l"
{ return AUTO; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 164 "lex.l"
{ return _BOOL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 165 "lex.l"
{ return BREAK; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 166 "lex.l"
{ return CASE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 167 "lex.l"
{ return CHAR; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 168 "lex.l"
{ return _COMPLEX; } 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 169 "lex.l"
{ return CONST;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 170 "lex.l"
{ return CONTINUE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 171 "lex.l"
{ return DEFAULT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 172 "lex.l"
{ return DO; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 173 "lex.l"
{ return DOUBLE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 174 "lex.l"
{ return ELSE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 175 "lex.l"
{ return ENUM; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 176 "lex.l"
{ return EXTERN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 177 "lex.l"
{ return FLOAT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 178 "lex.l"
{ return FOR; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 179 "lex.l"
{ return GOTO; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 180 "lex.l"
{ return IF; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 181 "lex.l"
{ return _IMAGINARY; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 182 "lex.l"
{ return INLINE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 183 "lex.l"
{ return INT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 184 "lex.l"
{ return LONG; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 185 "lex.l"
{ return REGISTER; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 186 "lex.l"
{ return RESTRICT; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 187 "lex.l"
{ return RETURN; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 188 "lex.l"
{ return SHORT; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 189 "lex.l"
{ return SIGNED; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 190 "lex.l"
{ return SIZEOF; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 191 "lex.l"
{ return STATIC; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 192 "lex.l"
{ return STRUCT; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 193 "lex.l"
{ return SWITCH; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 194 "lex.l"
{ return TYPEDEF; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 195 "lex.l"
{ return UNION; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 196 "lex.l"
{ return UNSIGNED; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 197 "lex.l"
{ return VOID; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 198 "lex.l"
{ return VOLATILE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 199 "lex.l"
{ return WHILE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 201 "lex.l"
{ return INDSEL;  } 
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 202 "lex.l"
{ return PLUSPLUS; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 203 "lex.l"
{ return MINUSMINUS; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 204 "lex.l"
{ return SHL; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 205 "lex.l"
{ return SHR; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 206 "lex.l"
{ return LTEQ; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 207 "lex.l"
{ return GTEQ; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 208 "lex.l"
{ return EQEQ; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 209 "lex.l"
{ return NOTEQ; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 210 "lex.l"
{ return LOGAND; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 211 "lex.l"
{ return LOGOR; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 212 "lex.l"
{ return ELLIPSIS; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 213 "lex.l"
{ return TIMESEQ; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 214 "lex.l"
{ return DIVEQ; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 215 "lex.l"
{ return MODEQ; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 216 "lex.l"
{ return PLUSEQ; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 217 "lex.l"
{ return MINUSEQ; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 218 "lex.l"
{ return SHLEQ; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 219 "lex.l"
{ return SHREQ; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 220 "lex.l"
{ return ANDEQ; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 221 "lex.l"
{ return OREQ; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 222 "lex.l"
{ return XOREQ; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 225 "lex.l"
{ return '!'; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 226 "lex.l"
{ return '^'; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 227 "lex.l"
{ return '&'; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 228 "lex.l"
{ return '*'; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 229 "lex.l"
{ return '-'; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 230 "lex.l"
{ return '+'; }              
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 231 "lex.l"
{ return '='; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 232 "lex.l"
{ return '~'; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 233 "lex.l"
{ return '|'; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 234 "lex.l"
{ return '.'; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 235 "lex.l"
{ return '<'; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 236 "lex.l"
{ return '>'; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 237 "lex.l"
{ return '/'; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 238 "lex.l"
{ return '?'; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 239 "lex.l"
{ return '('; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 240 "lex.l"
{ return ')'; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 241 "lex.l"
{ return '['; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 242 "lex.l"
{ return ']'; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 243 "lex.l"
{ return ','; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 244 "lex.l"
{ return ';'; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 245 "lex.l"
{ return ':'; }     
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 247 "lex.l"
{ yylval.string_literal = strdup(yytext); return IDENT; /* put somewhere */ }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 248 "lex.l"
{ printf("Error unrecognized token\n"); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 249 "lex.l"
ECHO;
	YY_BREAK
#line 1836 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(charseq):
case YY_STATE_EOF(str):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 327 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 327 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 326);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 249 "lex.l"

int yywrap() {}
int main() {
int t = yylex();
int x = 0;
if(t && x == 0)
{printf("%d %s %f %s\n", t, yylval.string_literal, yylval.finteger, yylval.type);
    x++;
}
}

