
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 153
#define YY_END_OF_BUFFER 154
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[347] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  154,  152,
       70,    1,  130,   53,  152,  152,  132,   36,  144,  145,
      133,  135,  148,  134,  139,  142,    6,    6,  150,  149,
      140,  136,  141,  143,  151,  151,  146,  147,  131,  151,
      151,  151,  151,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  138,  137,   51,   52,   37,
       52,   57,   69,   54,   57,   69,    5,    4,    3,   70,
      116,    0,  122,  117,  127,  120,  109,  123,  110,  124,
      108,    0,   24,    0,  121,    8,   24,   18,    0,    0,
        0,    7,    9,    0,    8,    6,    6,  111,  113,  115,

      114,  112,    0,  151,  151,  129,  151,  151,  151,  151,
      151,  151,  151,  151,  151,   80,  151,  151,  151,  151,
      151,  151,   88,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,  128,  118,   48,   38,   39,   47,
       50,   41,   42,   43,   49,   44,   45,   46,    0,   65,
       66,   55,   64,   68,   58,   59,   60,   67,   61,   62,
       63,    0,    0,  119,    0,   25,   26,    0,   24,   20,
       19,   21,   20,    0,   27,   11,   10,   12,  125,  126,
      151,  151,  151,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,   86,  151,  151,   91,  151,  151,

      151,  151,  151,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,   38,   40,   55,   56,    0,    0,
       24,    0,   30,   23,   22,   27,   28,   29,   14,    0,
       13,    0,   15,   12,  151,  151,  151,   71,  151,   74,
       75,  151,  151,  151,  151,   82,   83,  151,  151,   87,
      151,   92,  151,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,  105,  151,  151,   38,   40,   55,
       56,    2,   24,   31,   32,   28,    0,    0,   33,   17,
       16,   72,  151,  151,   73,   77,  151,  151,  151,  151,
       85,  151,  151,  151,  151,   96,  151,  151,  151,  151,

      151,  151,  103,  151,  151,  107,   25,   34,   35,  151,
      151,  151,  151,   81,   84,   90,  151,  151,   95,   97,
       98,   99,  100,  101,  151,  151,  151,  151,  151,  151,
       79,  151,  151,  102,  151,  151,   76,  151,   78,   93,
       94,  104,  106,  151,   89,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   28,   31,   32,
       33,   33,   34,   33,   33,   35,   33,   33,   33,   36,
       33,   33,   33,   33,   37,   33,   33,   38,   33,   33,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   33,   53,   54,   55,   56,
       57,   58,   33,   59,   60,   61,   62,   63,   64,   65,
       66,   67,    1,   68,    1,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    3,
        3,    1,    1,    1,    4,    1,    1,    3,    3,    3,
        3,    3,    5,    5,    5,    6,    5,    5,    1,    1,
        1,    1,    5,    3,    3,    3,    3,    3,    3,    5,
        5,    5,    5,    5,    5,    5,    5,    6,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    7,    1
    } ;

static const flex_int16_t yy_base[359] =
    {   0,
        0,    0,   67,   68,   69,   70,   76,   77,  381,  987,
       84,  987,  352,  987,  371,  348,   65,  987,  987,  987,
      339,   67,  987,   71,   74,  336,  100,   85,  987,  987,
       74,  296,   75,  987,  152,   72,  987,  987,  292,  122,
      204,   54,  113,   79,  123,  101,   85,  159,  149,  126,
      178,  143,  170,  150,  142,  187,  987,  987,  987,  987,
      263,  987,  987,  987,  987,  323,  987,  987,  987,  120,
      987,  224,  987,  987,  987,  987,  987,  987,  987,  987,
      987,  280,  370,  205,  987,  987,  238,  276,  250,  101,
      285,  987,  280,    0,  108,   94,    0,  268,  987,  987,

      987,  252,  230,  169,  169,  987,  197,  211,  263,  259,
      268,  129,  196,  269,  143,  277,  272,  292,  335,  278,
      306,  336,  283,  359,  339,  361,  366,  342,  391,  395,
      368,  408,  413,  414,  987,  330,  987,  241,  350,  987,
      987,  987,  987,  987,  987,  987,  987,  987,    0,  987,
      987,  183,  987,  987,  987,  987,  987,  987,  987,  987,
      987,    0,  433,  987,  425,  415,  987,  458,  220,  987,
      987,  445,  332,  450,  470,  987,  987,  479,  987,  987,
      432,  438,  441,  470,  477,  475,  458,  471,  318,  480,
      481,  487,  486,  478,  484,  493,  501,  490,  494,  511,

      503,  513,  518,  534,  519,  523,  539,  542,  540,  543,
      553,  548,  549,  555,  577,    0,  374,    0,  213,  593,
      599,  605,  608,  987,  987,  614,  341,  987,  987,  404,
      987,  634,  625,    0,  577,  598,  615,  605,  621,  622,
      624,  627,  634,  154,  642,  635,  641,  647,  644,  650,
      652,  653,  654,  658,  660,  655,  659,  667,  661,  665,
      684,  687,  680,  681,  664,  677,  708,  720,  987,  987,
      987,  987,  738,  987,  987,  987,  546,  723,  742,  987,
      987,  682,  683,  729,  730,  736,  737,  747,  751,  750,
      743,  752,  748,  755,  754,  749,  761,  763,  767,  765,

      773,  766,  762,  769,  786,  768,  987,  987,  987,  804,
      771,  778,  815,  777,  785,  811,  825,  831,  826,  827,
      830,  832,  833,  834,  838,  840,  842,  839,  841,  843,
      844,  846,  852,  847,  850,  869,  848,  863,  851,  853,
      857,  858,  861,  864,  865,  987,  937,  944,  951,  957,
      963,  969,  974,  175,  158,  131,  100,  979
    } ;

static const flex_int16_t yy_def[359] =
    {   0,
      346,    1,  347,  347,  348,  348,  349,  349,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  350,  346,  346,   27,  346,  346,
      346,  346,  346,  346,  351,  351,  346,  346,  346,  351,
      351,   41,   41,   41,   41,   41,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  352,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  350,  346,  346,   83,   27,  352,  352,
      352,  346,  346,  353,  352,   28,   28,  346,  346,  346,

      346,  346,  350,   41,  351,  346,  351,  351,  351,  351,
      351,   41,  351,  351,   41,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  346,  352,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  354,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  355,  346,  346,  350,  350,  346,  346,   87,  346,
      346,  346,  352,  346,   91,  346,  346,  353,  346,  346,
      351,  351,  351,  351,  351,  351,  351,  351,   41,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  346,  356,  346,  357,  346,  346,
       83,  346,  346,  346,  346,  346,  352,  346,  346,  358,
      346,  346,  346,  178,  351,  351,  351,  351,  351,  351,
      351,  351,  351,   41,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  358,  346,  346,  346,
      346,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  346,  346,  346,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,    0,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346
    } ;

static const flex_int16_t yy_nxt[1057] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       28,   29,   30,   31,   32,   33,   34,   35,   35,   35,
       35,   35,   36,   36,   36,   36,   36,   36,   37,   10,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       36,   48,   36,   49,   36,   36,   36,   36,   50,   51,
       52,   53,   54,   55,   36,   36,   36,   56,   57,   59,
       59,   63,   63,   74,   64,   64,   60,   60,   68,   68,
       77,   69,   69,   65,   65,   70,   79,   70,  346,   75,
       82,   78,   83,   83,   83,   80,   81,   98,   99,  101,

      102,  346,  271,   96,   97,   97,   61,   61,   66,   66,
       86,   86,  111,   96,   96,  105,   87,  103,   88,   88,
       89,   70,  346,   70,  103,  346,  115,   90,   90,   90,
       91,   90,  346,  269,   92,  116,   93,   94,  346,  346,
      105,  122,  346,   90,   90,   90,   90,   91,   90,  346,
      107,  108,  346,   92,  120,  109,  112,  121,  346,  346,
      218,   93,  105,  113,   94,  346,  346,   95,  103,  114,
      104,  104,  104,  126,  105,  346,  117,  216,  118,  104,
      104,  104,  104,  104,  105,  346,  346,  119,  186,  346,
      105,  189,  134,  346,  346,  104,  104,  104,  104,  104,

      104,  217,  217,  103,  105,  125,  133,  123,  131,  346,
      346,  135,  346,  346,  124,  288,  346,  346,  272,   90,
      103,  346,  104,  104,  104,  132,  346,  346,  127,  128,
      105,  104,  104,  104,  104,  104,  346,  346,  129,  187,
      168,  130,  163,  163,  163,  346,  346,  104,  104,  104,
      104,  104,  104,  181,  136,  168,  169,  169,  169,  215,
      215,  139,  168,  346,  346,  110,   87,  182,   89,   89,
       89,   90,  137,  346,  346,  346,  180,  168,  346,  346,
       91,  138,  138,  139,  346,  346,  170,  170,  346,  140,
      176,  176,  179,  346,  346,  346,  164,   91,  174,  346,

      174,  103,  141,  175,  175,  175,  142,  143,  346,  346,
      171,  144,  172,  346,  177,  185,  106,  183,  145,  184,
      100,  146,  346,  147,  188,  148,  346,  149,  150,  171,
      346,  191,  151,  177,  194,  346,  346,  172,  190,  346,
      346,  152,  152,  173,  346,  346,  103,  176,  103,  153,
      346,  346,  346,  192,  346,  346,  346,  103,  346,  346,
       85,  244,  154,   76,  195,  346,  155,  156,  139,  139,
      139,  157,   73,  346,   72,  346,   71,  346,  158,  105,
      346,  159,  346,  160,  346,  161,  346,  162,   83,   83,
       83,  204,  270,  270,  199,  193,  196,   84,   84,   84,

      165,  166,  346,  346,  167,  168,  346,  346,  205,  346,
      200,  346,  197,   84,   84,   84,   84,  165,  166,  198,
      201,  202,  203,  167,  346,  209,  346,  168,  346,  346,
      346,  346,  346,  346,  206,  346,  219,   84,  220,  168,
      220,  346,  346,  221,  221,  221,  208,  346,  346,  207,
      168,  163,  163,  163,  346,  224,  224,  346,  346,  210,
      168,  168,  346,  346,  212,  214,  213,  211,  226,  226,
      226,  222,  168,  222,  346,  346,  223,  223,  223,  225,
      346,  346,  168,  346,  237,  346,  346,  346,  235,  229,
      229,  346,  236,  346,  346,  230,  346,  346,  225,  346,

      346,  227,  346,  346,  228,  346,  346,  346,  346,  346,
      346,  346,  224,  231,  232,  233,  241,  346,  227,  346,
      239,  249,  240,  228,  245,  346,  238,  346,  246,  346,
      242,  243,  231,  248,  346,  346,  232,  346,  346,  346,
      233,  247,  346,  252,  346,  346,  234,  346,  346,  250,
      346,  346,  251,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  253,  254,  346,  346,  258,  346,  346,  346,
      346,  346,  346,  346,  255,  346,  256,  346,  346,  346,
      346,  168,  346,  259,  346,  346,  346,  262,  346,  257,
      346,  346,  266,  346,  265,  268,  268,  139,  346,  263,

      260,  346,  261,  168,  264,  346,  346,  346,  267,  346,
      346,  273,  273,  273,  346,  346,  346,  221,  221,  221,
      346,  346,  346,  223,  223,  223,  223,  223,  223,   84,
      282,  346,  226,  226,  226,  280,  280,  346,  346,  274,
      346,  346,  275,  346,  346,  276,   84,  278,  228,  278,
      346,  346,  279,  279,  279,  283,  274,  346,  346,  281,
      346,  275,  276,  346,  284,  346,  346,  228,  346,  346,
      346,  346,  346,  285,  346,  346,  346,  346,  281,  346,
      346,  346,  346,  346,  346,  287,  346,  286,  346,  346,
      346,  346,  280,  346,  346,  289,  346,  346,  346,  346,

      346,  346,  346,  346,  291,  290,  297,  292,  346,  346,
      300,  346,  299,  293,  346,  296,  294,  346,  295,  346,
      346,  346,  346,  298,  346,  346,  346,  346,  346,  301,
      304,  346,  346,  302,  346,  303,  310,  305,  139,  139,
      139,  279,  279,  279,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  306,  273,  273,  273,  346,
      279,  279,  279,  346,  346,  346,  346,  346,  346,  307,
      346,  346,  167,  308,  346,  346,  309,  346,  346,  346,
      311,  346,  346,  346,  346,  346,  307,  346,  346,  346,
      308,  167,  312,  346,  346,  309,  346,  346,  314,  316,

      313,  346,  346,  346,  346,  315,  318,  320,  317,  319,
      346,  321,  322,  325,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  324,  326,  323,  329,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  327,  346,  330,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  328,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  332,  346,  346,  331,  333,  346,  346,  346,
      346,  346,  346,  346,  338,  346,  334,  335,  346,  346,
      339,  346,  346,  346,  346,  336,  342,  346,  346,  346,

      346,  346,  346,  337,  340,  346,  346,  346,  346,  346,
      346,  346,  341,  346,  346,  346,  343,  346,  346,  346,
      346,  344,  346,  346,  346,  346,  346,  346,  346,  345,
      346,  346,  346,  346,  346,  346,  346,   58,   58,   58,
       58,   58,   58,   58,   62,   62,   62,   62,   62,   62,
       62,   67,   67,   67,   67,   67,   67,   67,   84,   84,
      346,  346,  346,   84,  105,  105,  346,  105,  105,  105,
       90,   90,   90,  346,  346,   90,  178,  346,  346,  346,
      178,  277,  346,  346,  277,  277,    9,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346
    } ;

static const flex_int16_t yy_chk[1057] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    5,    6,   17,    5,    6,    3,    4,    7,    8,
       22,    7,    8,    5,    6,   11,   24,   11,   36,   17,
       25,   22,   25,   25,   25,   24,   24,   31,   31,   33,

       33,   47,  357,   28,   28,   28,    3,    4,    5,    6,
       27,   27,   42,   96,   96,   42,   27,   90,   27,   27,
       27,   70,   28,   70,   95,   90,   44,   27,   27,   27,
       27,   27,   95,  356,   27,   44,   27,   27,   40,   36,
       44,   47,   50,   27,   27,   27,   27,   27,   27,   28,
       40,   40,   47,   27,   46,   40,   43,   46,   55,   52,
      355,   27,   46,   43,   27,   49,   54,   27,   35,   43,
       35,   35,   35,   50,   43,   48,   45,  354,   45,   35,
       35,   35,   35,   35,   45,  105,   53,   45,  112,   40,
      112,  115,   55,   50,   51,   35,   35,   35,   35,   35,

       35,  152,  152,   56,  115,   49,   54,   48,   52,   55,
       52,   56,  113,  107,   48,  244,   49,   54,  219,   35,
       41,   84,   41,   41,   41,   53,   48,  108,   51,   51,
      104,   41,   41,   41,   41,   41,  105,   53,   51,  113,
       84,   51,   72,   72,   72,   51,  103,   41,   41,   41,
       41,   41,   41,  107,   56,  169,   87,   87,   87,  138,
      138,  138,   84,  113,  107,   41,   89,  108,   89,   89,
       89,   41,   61,   87,   89,  110,  102,  169,  108,  109,
       89,   61,   61,   61,  111,  114,   88,   88,  117,   61,
       93,   93,   98,  116,  120,   87,   82,   89,   91,  123,

       91,   91,   61,   91,   91,   91,   61,   61,  118,   91,
       88,   61,   88,   88,   93,  111,   39,  109,   61,  110,
       32,   61,  121,   61,  114,   61,  110,   61,   66,   88,
      109,  117,   66,   93,  120,  111,  114,   88,  116,  117,
       88,   66,   66,   88,  116,  120,  136,   93,  173,   66,
      123,  119,  122,  118,  136,  125,  173,  227,  128,  118,
       26,  189,   66,   21,  121,  227,   66,   66,  139,  139,
      139,   66,   16,  121,   15,  124,   13,  126,   66,  189,
        9,   66,  127,   66,  131,   66,    0,   66,   83,   83,
       83,  128,  217,  217,  125,  119,  122,   83,   83,   83,

       83,   83,  119,  122,   83,   83,  125,  129,  128,  128,
      126,  130,  124,   83,   83,   83,   83,   83,   83,  124,
      126,  126,  127,   83,  132,  131,  124,   83,  126,  133,
      134,  166,    0,  127,  129,  131,  163,   83,  165,  230,
      165,  165,    0,  165,  165,  165,  130,    0,  181,  129,
      166,  163,  163,  163,  182,  172,  172,  183,  129,  132,
      165,  230,  130,    0,  133,  134,  133,  132,  174,  174,
      174,  168,  166,  168,  187,  132,  168,  168,  168,  172,
      133,  134,  165,  175,  183,  175,  184,  188,  181,  178,
      178,  186,  182,  185,  194,  178,  190,  191,  172,  181,

      195,  175,  193,  192,  175,  182,  198,    0,  183,  196,
      199,    0,  172,  178,  178,  178,  187,  197,  175,  201,
      185,  194,  186,  175,  190,  187,  184,  200,  191,  202,
      188,  188,  178,  193,  203,  205,  178,  184,  188,  206,
      178,  192,  186,  199,  185,  194,  178,  190,  191,  196,
      204,  195,  197,  193,  192,  207,  209,  198,  208,  210,
      196,  199,  200,  201,  212,  213,  205,    0,  197,  211,
      201,  214,    0,    0,  202,    0,  203,    0,  200,    0,
      202,  277,    0,  206,    0,  203,  205,  209,    0,  204,
      206,    0,  213,  235,  212,  215,  215,  215,    0,  210,

      207,  204,  208,  277,  211,    0,  207,  209,  214,  208,
      210,  220,  220,  220,  236,  212,  213,  221,  221,  221,
      211,  238,  214,  222,  222,  222,  223,  223,  223,  221,
      235,  237,  226,  226,  226,  233,  233,  239,  240,  223,
      241,    0,  223,  242,  235,  226,  221,  232,  226,  232,
      243,  246,  232,  232,  232,  236,  223,  247,  245,  233,
      249,  223,  226,  248,  237,  236,  250,  226,  251,  252,
      253,  256,  238,  239,  254,  257,  255,  259,  233,    0,
      265,  260,  237,  258,    0,  243,    0,  242,  239,  240,
        0,  241,  233,  266,  242,  245,  263,  264,  282,  283,

      261,  243,  246,  262,  249,  248,  257,  251,  247,  245,
      260,  249,  259,  253,  248,  256,  254,  250,  255,  251,
      252,  253,  256,  258,  267,  254,  257,  255,  259,  261,
      264,  265,  260,  262,  258,  263,  283,  266,  268,  268,
      268,  278,  278,  278,  266,  284,  285,  263,  264,  282,
      283,  261,  286,  287,  262,  267,  273,  273,  273,  291,
      279,  279,  279,  288,  293,  296,  290,  289,  292,  273,
      295,  294,  273,  279,    0,  267,  279,  297,  303,  298,
      284,  300,  302,  299,  306,  304,  273,  311,    0,  301,
      279,  273,  287,  314,  312,  279,  284,  285,  289,  292,

      288,  315,  305,  286,  287,  290,  294,  297,  293,  295,
      291,  298,  299,  302,  288,  293,  296,  290,  289,  292,
      310,  295,  294,  301,  304,  300,  311,  316,  297,  303,
      298,  313,  300,  302,  299,  306,  304,  305,  311,  312,
      301,  317,  319,  320,  314,  312,  321,  318,  322,  323,
      324,  310,  315,  305,  325,  328,  326,  329,  327,  330,
      331,    0,  332,  334,  337,    0,  335,  339,  333,  340,
        0,  310,  317,  341,  342,  313,  318,  343,  316,  338,
      344,  345,  313,    0,  329,  336,  325,  326,    0,    0,
      330,    0,  317,  319,  320,  327,  335,  321,  318,  322,

      323,  324,    0,  328,  332,  325,  328,  326,  329,  327,
      330,  331,  333,  332,  334,  337,  336,  335,  339,  333,
      340,  338,    0,    0,  341,  342,    0,    0,  343,  344,
      338,  344,  345,    0,    0,    0,  336,  347,  347,  347,
      347,  347,  347,  347,  348,  348,  348,  348,  348,  348,
      348,  349,  349,  349,  349,  349,  349,  349,  350,  350,
        0,    0,    0,  350,  351,  351,    0,  351,  351,  351,
      352,  352,  352,    0,    0,  352,  353,    0,    0,    0,
      353,  358,    0,    0,  358,  358,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 4 "lex.l"
   #include <stdlib.h>
   #include <stdio.h>
   #include "tokens-manual.h"
   #include <ctype.h>
   int get_line_info();
   int handle_error();
   int lineno;
     enum type {
        INT_SIGNED,
        INT_LONG,
        INT_LONGLONG,
        INT_UNSIGNED,
        INT_ULONG,
        INT_ULONGLONG,
        FLOATV,
        DOUBLEV,
        DOUBLE_LONG,
    };
       struct Num  {
    unsigned long long integer;
     long double fvalue;
     enum type type;
 
   };
   union yylval {
    char *string_literal;
    char charlit;
    struct Num num;
   
   };
 

   typedef union yylval YYSTYPE;
   YYSTYPE yylval;
    char filename_buf[256];
    char *filename_buf_ptr;
    int string_buf_len = 0;
        
#line 828 "lex.yy.c"

#line 830 "lex.yy.c"

#define INITIAL 0
#define charseq 1
#define str 2
#define filename 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 66 "lex.l"


#line 69 "lex.l"
    char string_buf[1024]; 
    char charvalue;
    char *string_buf_ptr;
    int char_count; 
    int count = 0;
#line 1059 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 347 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 987 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 74 "lex.l"
{ lineno++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 75 "lex.l"
{ count = 0; filename_buf_ptr = filename_buf; lineno = 0;  BEGIN(filename);  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 78 "lex.l"
{ 
    count++;
    if(count == 1) {
     *filename_buf_ptr = '\0'; 
    }
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 84 "lex.l"
{BEGIN(INITIAL); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "lex.l"
{ *filename_buf_ptr++ = yytext[0];  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "lex.l"
{ yylval.num.integer= atoi(yytext); yylval.num.type = INT_SIGNED; return NUMBER; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 90 "lex.l"
{ yylval.num.integer = atol(yytext); yylval.num.type =  INT_LONG; return NUMBER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 91 "lex.l"
{ yylval.num.integer = atoll(yytext); yylval.num.type = INT_LONGLONG; return NUMBER; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 92 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 10); yylval.num.type = INT_UNSIGNED; return NUMBER; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 93 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 10); yylval.num.type = INT_ULONG; return NUMBER; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 94 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 10); yylval.num.type = INT_ULONGLONG; return NUMBER; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 96 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 16);  yylval.num.type = INT_SIGNED; return NUMBER; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 97 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 16); yylval.num.type = INT_LONG; return NUMBER; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 98 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 16); yylval.num.type = INT_LONGLONG; return NUMBER; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 99 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 16); yylval.num.type = INT_UNSIGNED; return NUMBER; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 100 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 16); yylval.num.type = INT_ULONG; return NUMBER; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 101 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 16); yylval.num.type = INT_ULONGLONG; return NUMBER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 8); yylval.num.type = INT_SIGNED; return NUMBER; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "lex.l"
{ yylval.num.integer = strtoul(yytext, NULL, 8); yylval.num.type = INT_LONG; return NUMBER; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 105 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 8); yylval.num.type = INT_LONGLONG; return NUMBER; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 106 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 8); yylval.num.type = INT_UNSIGNED; return NUMBER; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 107 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 8); yylval.num.type = INT_ULONG; return NUMBER; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 108 "lex.l"
{ yylval.num.integer = strtoull(yytext, NULL, 8); yylval.num.type =  INT_ULONGLONG; return NUMBER; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type = DOUBLEV;  return NUMBER;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type =  FLOATV; return NUMBER; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type =  DOUBLE_LONG; return NUMBER; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 114 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type =  DOUBLEV; return NUMBER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 115 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type = FLOATV; return NUMBER; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 116 "lex.l"
{ yylval.num.fvalue = atof(yytext); yylval.num.type = DOUBLE_LONG; return NUMBER; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 118 "lex.l"
{ yylval.num.fvalue = strtod(yytext, NULL); yylval.num.type = DOUBLEV; return NUMBER; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 119 "lex.l"
{ yylval.num.fvalue = strtold(yytext, NULL); yylval.num.type = FLOATV; return NUMBER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "lex.l"
{ yylval.num.fvalue = strtold(yytext, NULL); yylval.num.type = DOUBLE_LONG; return NUMBER; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "lex.l"
{ yylval.num.fvalue = strtod(yytext, NULL); yylval.num.type = DOUBLEV; return NUMBER; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 123 "lex.l"
{ yylval.num.fvalue = strtold(yytext, NULL); yylval.num.type = FLOATV; return NUMBER; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 124 "lex.l"
{ yylval.num.fvalue = strtold(yytext, NULL); yylval.num.type = DOUBLE_LONG; return NUMBER; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 127 "lex.l"
{   char_count = 0; BEGIN(charseq); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 128 "lex.l"
{ BEGIN(INITIAL); 
              if(char_count == 0) {
                fprintf(stderr, "Error multibyte char onfdasdfly first value was used \n");
              }  
              if(char_count > 1) {
                fprintf(stderr, "Error multibyte char only first value was used\n");
              }
              printf("%d", charvalue); //!!!!CHANGE TO RETURN AND SET YYVAL PROPERLY!!!
              yylval.charlit = charvalue;
              return CHARLIT;
              }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 139 "lex.l"
{
    int result;
    if (char_count == 0) {
    printf("GETTING OCTAL\n");
    sscanf(yytext + 1, "%o", &result);
    charvalue = result; 
    }
    char_count++;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 148 "lex.l"
{
    printf("invalid octal");
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 151 "lex.l"
{
   
      int result;
      yytext[0] = '0';
    if (char_count == 0) {
    printf("GETTING HEX\n");
    sscanf(yytext, "%x", &result);
    charvalue = result; 
    }
    char_count++;
    
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 163 "lex.l"
{  if(char_count == 0) charvalue = '\a'; char_count++; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 164 "lex.l"
{  if(char_count == 0) charvalue = '\b'; char_count++; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 165 "lex.l"
{  if(char_count == 0) charvalue = '\f'; char_count++; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 166 "lex.l"
{  if(char_count == 0) charvalue = '\r'; char_count++; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 167 "lex.l"
{  if(char_count == 0) charvalue = '\t'; char_count++; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 168 "lex.l"
{  if(char_count == 0) charvalue = '\v'; char_count++; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 169 "lex.l"
{  if(char_count == 0) charvalue = '\?'; char_count++; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 170 "lex.l"
{  if(char_count == 0) charvalue = '\''; char_count++; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 171 "lex.l"
{  if(char_count == 0) charvalue = '\n'; char_count++; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 172 "lex.l"
{  if(char_count == 0) charvalue = '\\'; char_count++; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 173 "lex.l"
{

    int result;
    if(char_count == 0) {
        printf("GETTING SC \n"); 
        charvalue = yytext[0];
    }
    char_count++;
}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 183 "lex.l"
{
    printf("Error invalid value in char seq");
}    
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 187 "lex.l"
{string_buf_ptr = string_buf; BEGIN(str);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 189 "lex.l"
{BEGIN(INITIAL); 
    *string_buf_ptr = '\0';
  printf("%s\n", string_buf);
  string_buf_len = string_buf_ptr - string_buf;
  yylval.string_literal = strdup(string_buf);
  return STRING;
   }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 196 "lex.l"
{
    int result;
    sscanf(yytext+1, "%o", &result);
    *string_buf_ptr++ = result;

}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 202 "lex.l"
{
    int result;
    yytext[0] = '0';
    printf("GETTING HEX\n");
    sscanf(yytext, "%x", &result);
    *string_buf_ptr++ = result;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 209 "lex.l"
{
    *string_buf_ptr++ = yytext[0];
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 213 "lex.l"
{  *string_buf_ptr++ = '\a';}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 214 "lex.l"
{   *string_buf_ptr++ = '\b';}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 215 "lex.l"
{   *string_buf_ptr++ = '\f'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 216 "lex.l"
{   *string_buf_ptr++ = '\r'; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 217 "lex.l"
{   *string_buf_ptr++ = '\t'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 218 "lex.l"
{   *string_buf_ptr++ = '\v'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 219 "lex.l"
{   *string_buf_ptr++ = '\?'; printf("hi");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 220 "lex.l"
{   *string_buf_ptr++ = '\"'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 221 "lex.l"
{   *string_buf_ptr++ = '\''; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 222 "lex.l"
{   *string_buf_ptr++ = '\n'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 223 "lex.l"
{   *string_buf_ptr++ = '\\'; }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 225 "lex.l"
{
    printf("Error Invalid sequence in string\n");
}   
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 228 "lex.l"
{ ; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 229 "lex.l"
{ return AUTO; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 230 "lex.l"
{ return _BOOL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 231 "lex.l"
{ return BREAK; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 232 "lex.l"
{ return CASE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 233 "lex.l"
{ return CHAR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 234 "lex.l"
{ return _COMPLEX; } 
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 235 "lex.l"
{ return CONST;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 236 "lex.l"
{ return CONTINUE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 237 "lex.l"
{ return DEFAULT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 238 "lex.l"
{ return DO; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 239 "lex.l"
{ return DOUBLE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 240 "lex.l"
{ return ELSE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 241 "lex.l"
{ return ENUM; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 242 "lex.l"
{ return EXTERN; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 243 "lex.l"
{ return FLOAT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 244 "lex.l"
{ return FOR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 245 "lex.l"
{ return GOTO; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 246 "lex.l"
{ return IF; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 247 "lex.l"
{ return _IMAGINARY; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 248 "lex.l"
{ return INLINE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 249 "lex.l"
{ return INT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 250 "lex.l"
{ return LONG; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 251 "lex.l"
{ return REGISTER; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 252 "lex.l"
{ return RESTRICT; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 253 "lex.l"
{ return RETURN; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 254 "lex.l"
{ return SHORT; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 255 "lex.l"
{ return SIGNED; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 256 "lex.l"
{ return SIZEOF; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 259 "lex.l"
{ return STATIC; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 260 "lex.l"
{ return STRUCT; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 261 "lex.l"
{ return SWITCH; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 262 "lex.l"
{ return TYPEDEF; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 263 "lex.l"
{ return UNION; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 264 "lex.l"
{ return UNSIGNED; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 265 "lex.l"
{ return VOID; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 266 "lex.l"
{ return VOLATILE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 267 "lex.l"
{ return WHILE; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 269 "lex.l"
{ return INDSEL;  } 
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 270 "lex.l"
{ return PLUSPLUS; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 271 "lex.l"
{ return MINUSMINUS; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 272 "lex.l"
{ return SHL; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 273 "lex.l"
{ return SHR; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 274 "lex.l"
{ return LTEQ; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 275 "lex.l"
{ return GTEQ; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 276 "lex.l"
{ return EQEQ; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 277 "lex.l"
{ return NOTEQ; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 278 "lex.l"
{ return LOGAND; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 279 "lex.l"
{ return LOGOR; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 280 "lex.l"
{ return ELLIPSIS; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 281 "lex.l"
{ return TIMESEQ; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 282 "lex.l"
{ return DIVEQ; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 283 "lex.l"
{ return MODEQ; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 284 "lex.l"
{ return PLUSEQ; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 285 "lex.l"
{ return MINUSEQ; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 286 "lex.l"
{ return SHLEQ; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 287 "lex.l"
{ return SHREQ; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 288 "lex.l"
{ return ANDEQ; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 289 "lex.l"
{ return OREQ; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 290 "lex.l"
{ return XOREQ; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 293 "lex.l"
{ return '!'; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 294 "lex.l"
{ return '^'; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 295 "lex.l"
{ return '&'; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 296 "lex.l"
{ return '*'; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 297 "lex.l"
{ return '-'; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 298 "lex.l"
{ return '+'; }              
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 299 "lex.l"
{ return '='; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 300 "lex.l"
{ return '~'; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 301 "lex.l"
{ return '|'; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 302 "lex.l"
{ return '.'; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 303 "lex.l"
{ return '<'; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 304 "lex.l"
{ return '>'; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 305 "lex.l"
{ return '/'; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 306 "lex.l"
{ return '?'; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 307 "lex.l"
{ return '('; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 308 "lex.l"
{ return ')'; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 309 "lex.l"
{ return '['; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 310 "lex.l"
{ return ']'; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 311 "lex.l"
{ return ','; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 312 "lex.l"
{ return ';'; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 313 "lex.l"
{ return ':'; }     
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 315 "lex.l"
{ yylval.string_literal = strdup(yytext); return IDENT; /* put somewhere */ }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 316 "lex.l"
{ fprintf(stderr, "Error unrecognized token : %s\n", yytext); }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 317 "lex.l"
ECHO;
	YY_BREAK
#line 1952 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(charseq):
case YY_STATE_EOF(str):
case YY_STATE_EOF(filename):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 347 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 347 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 346);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 317 "lex.l"

int get_line_info(){
    printf("got here at least");
    lineno = 0;
    
}
// print filename, line number and the incorrect token
// int handle_error(){
//     fprintf(stderr, "Error in file %s on line number %d: %s\n", filename, lineno, yytext);
// }
void charhelper(char val) {
    switch(val) {
        case '\a': printf("\a"); break;
        case '\b': printf("\\b"); break;
        case '\f': printf("\\f"); break;
        case '\n': printf("\\n"); break;
        case '\r': printf("\\r"); break;
        case '\t': printf("\\t"); break;
        case '\v': printf("\\v"); break;
        default: printf("\\%03o", val);
    }
}
int yywrap() {}
int main() {
    int t;
while(t = yylex())  {
   printf("%s \t\t %d \t\t",filename_buf, lineno);  
    switch(t) 
    {
        case AUTO:               printf("AUTO\n"); break;
        case _BOOL:             printf("_BOOL\n"); break;
        case BREAK:             printf("BREAK\n"); break;
        case CASE:              printf("CASE\n"); break;
        case CHAR:              printf("CHAR\n"); break;
        case _COMPLEX:          printf("_COMPLEX\n"); break;
        case CONST:             printf("CONST\n"); break;
        case CONTINUE:          printf("CONTINUE\n"); break;
        case DEFAULT:           printf("DEFAULT\n"); break;
        case DO:                printf("DO\n"); break;
        case DOUBLE:            printf("DOUBLE\n"); break;
        case ELSE:              printf("ELSE\n"); break;
        case ENUM:              printf("ENUM\n"); break;
        case EXTERN:            printf("EXTERN\n"); break;
        case FLOAT:             printf("Float\n"); break;
        case FOR:               printf("For\n"); break;
        case GOTO:              printf("Goto\n"); break;
        case IF:                printf("If\n"); break;
        case _IMAGINARY:        printf("_IMAGINARY\n"); break;
        case INLINE:            printf("Inline\n"); break;
        case INT:               printf("Int\n"); break;
        case LONG:              printf("Long\n"); break;
        case REGISTER:          printf("Register\n"); break;
        case RESTRICT:          printf("Restrict\n"); break;
        case RETURN:            printf("Return\n"); break;
        case SHORT:             printf("Short\n"); break;
        case SIGNED:            printf("Signed\n"); break;
        case SIZEOF:            printf("Sizeof\n"); break;
        case STATIC:            printf("Static\n"); break;
        case STRUCT:            printf("Struct\n"); break;
        case SWITCH:            printf("Switch\n"); break;
        case TYPEDEF:           printf("Typedef\n"); break;
        case UNION:             printf("Union\n"); break;
        case UNSIGNED:          printf("Unsigned\n"); break;
        case VOID:              printf("Void\n"); break;
        case VOLATILE:          printf("Volatile\n"); break;
        case WHILE:             printf("While\n"); break;
        case INDSEL:            printf("->\n"); break;
        case PLUSPLUS:          printf("++\n"); break;
        case MINUSMINUS:        printf("--\n"); break;
        case SHL:               printf("<<\n"); break;
        case SHR:               printf(">>\n"); break;
        case LTEQ:              printf("<=\n"); break;
        case GTEQ:              printf(">=\n"); break;
        case EQEQ:              printf("==\n"); break;
        case NOTEQ:             printf("!=\n"); break;
        case LOGAND:            printf("&&\n"); break;
        case LOGOR:             printf("||\n"); break;
        case ELLIPSIS:          printf("ELIPSIS\n"); break;
        case TIMESEQ:           printf("*=\n"); break;
        case DIVEQ:             printf("/=\n"); break;
        case MODEQ:             printf("\n"); break;
        case PLUSEQ:            printf("+=\n"); break;
        case MINUSEQ:           printf("-=\n"); break;
        case SHLEQ:             printf("<<=\n"); break;
        case SHREQ:             printf(">>=\n"); break;
        case ANDEQ:             printf("&=\n"); break;
        case OREQ:              printf("|=\n"); break;
        case XOREQ:             printf("^=\n"); break;
        case '!':               printf("!\n"); break;
        case '^':               printf("^\n"); break;
        case '&':               printf("&\n"); break;
        case '*':               printf("*\n"); break;
        case '-':               printf("-\n"); break;
        case '+':               printf("+\n"); break;
        case '=':               printf("=\n"); break;
        case '~':               printf("~\n"); break;
        case '|':               printf("|\n"); break;
        case '.':               printf(".\n"); break;
        case '<':               printf("<\n"); break;
        case '>':               printf(">\n"); break;
        case '/':               printf("/\n"); break;
        case '?':               printf("?\n"); break;
        case '(':               printf("(\n"); break;
        case ')':               printf(")\n"); break;
        case '[':               printf("[\n"); break;
        case ']':               printf("]\n"); break;
        case ',':               printf(",\n"); break;
        case ';':               printf(";\n"); break;
        case ':':               printf(":\n"); break;
        case IDENT:             printf("IDENT    %s\n", yylval.string_literal); break;
        case NUMBER:  printf("NUMBER:  "); switch(yylval.num.type) {
            case INT_SIGNED: printf(" \t INTEGER %d  \t INT\n", yylval.num.integer); break;
            case INT_LONG: printf(" \t INTEGER %d \t LONG INT\n", yylval.num.integer ); break;
            case INT_LONGLONG: printf(" \t INTEGER %d \t LONG LONG INT\n", yylval.num.integer ); break;
            case INT_ULONG: printf(" \t INTEGER %d \t UNSIGNED LONG INT\n", yylval.num.integer ); break;
            case INT_ULONGLONG: printf(" \t INTEGER %d \t UNSIGNED LONG LONG INT\n", yylval.num.integer ); break;
            case FLOATV: printf("\t REAL \t %Lf \t FLOAT\n", yylval.num.fvalue); break;
            case DOUBLEV: printf("\t REAL \t %Lf \t DOUBLE\n", yylval.num.fvalue); break;
            case DOUBLE_LONG: printf("\t REAL \t %Lf \t LONG DOUBLE\n", yylval.num.fvalue); break;

        } break;
        case CHARLIT: {
            printf("\t CHARLIT \t");
          if(isprint(yylval.charlit)) {
            if(yylval.charlit == '\'' || yylval.charlit == '\'' || yylval.charlit == '\"' || yylval.charlit == '\\' ) {
                printf("\\%c\n", yylval.charlit);
            } else {
            printf("%c\n", yylval.charlit); 
            }
          } else {
            charhelper(yylval.charlit);
            printf("\n");
          }
            
        } break;

       case STRING: { 
        printf("\t STRING \t");
        for(int i = 0; i < string_buf_len; i++) {
                if(isprint(yylval.string_literal[i])) {
            if(yylval.string_literal[i]== '\'' || yylval.string_literal[i] == '\'' || yylval.string_literal[i] == '\"' || yylval.string_literal[i] == '\\') {
                printf("\\%c", yylval.string_literal[i]);
            } else {
            printf("%c", yylval.string_literal[i]); 
            }
          } else {
            charhelper(yylval.string_literal[i]);
        
          }
              
        }
        printf("\n");
       } break;



        //we have to add the rest 
        default: printf("sussy\n");
    }
  
    
}

}

